List<String> list_field_tkqhxd=["Để được cấp chứng chỉ hành nghề hoạt động xây dựng, cá nhân phảiđáp ứng được điều kiện gì?",
  "a. Có trình độ chuyên môn phù hợp với nội dung đề nghị cấp chứng chỉ hànhnghề",
  "b. Có thời gian và kinh nghiệm tham gia công việc phù hợp với nội dung đềnghị cấp chứng chỉ hành nghề",
  "c. Đã qua sát hạch kiểm tra kinh nghiệm nghề nghiệp và kiến thức pháp luậtliên quan đến lĩnh vực hành nghề",
  "d. Tất cả các điều kiện trên",
  "d",
  " Cơ quan nào có trách nhiệm tổ chức lập quy hoạch xây dựng?",
  "a. Bộ Xây dựng",
  "b. Ủy ban nhân dân các cấp",
  "c. Chủ đầu tư dự án",
  "d. Bộ Xây dựng và Ủy ban nhân dân các cấp",
  "d",
  " Loại nào dưới đây là Quy hoạch xây dựng?",
  "a. Quy hoạch bảo quản, tu bổ, phục hồi di tích",
  "b. Quy hoạch chung Đô thị mới Nhơn Trạch, tỉnh Đồng Nai đến năm 2030,tầm nhìn đến năm 2050",
  "c. Quy hoạch hệ thống đô thị và nông thôn",
  "d. Quy hoạch chi tiết nhóm cảng biển, bến cảng, cầu cảng, bến phao, khunước, vùng nước",
  "b",
  " Công tác quy hoạch xây dựng bao gồm những công việc chủ yếu nàosau đây?",
  "a. Lập, phê duyệt nhiệm vụ và lập, phê duyệt đồ án quy hoạch xây dựng",
  "b. Tổ chức triển khai, quản lý thực hiện theo quy hoạch được duyệt",
  "c. Lập, xác định chi phí cho công tác quy hoạch",
  "d. Tất cả các nội dung trên",
  "d",
  " Cơ quan nào có thẩm quyền phê duyệt quy hoạch xây dựng vùng liêntỉnh?",
  "a. Thủ tướng Chính phủ",
  "b. Bộ Xây dựng",
  "c. Hội đồng nhân dân các huyện trong vùng lập quy hoạch",
  "d. Ủy ban nhân dân cấp Tỉnh",
  "d",
  " Cơ quan nào có thẩm quyền phê duyệt quy hoạch xây dựng vùnghuyện ?",
  "a. Ủy ban nhân dân tỉnh",
  "b. Ủy ban nhân dân huyện",
  "c. Hội đồng nhân dân tỉnh",
  "d. Bộ Xây dựng",
  "a",
  " Ủy ban nhân dân cấp Tỉnh có thẩm quyền phê duyệt các quy hoạch nàodưới đây:",
  "a. Toàn bộ các quy hoạch liệt kê dưới đây",
  "b. Quy hoạch xây dựng vùng liên huyện, vùng huyện",
  "c. Quy hoạch chung xây dựng khu chức năng, trừ các quy hoạch do Thủtướng Chính phủ giao Bộ Xây dựng tổ chức lập",
  "d. Quy hoạch phân khu xây dựng trong địa bàn tỉnh",
  "a",
  " Loại Quy hoạch xây dựng nào được quy định trong Luật Xây dựng 2014 ?",
  "a. Quy hoạch vùng liên huyện, vùng huyện",
  "b. Quy hoạch đô thị, quy hoạch nông thôn",
  "c. Quy hoạch khu chức năng",
  "d. Tất cả các loại trên",
  "d",
  " Trình tự lập, phê duyệt quy hoạch xây dựng?",
  "a. Lập, phê duyệt Nhiệm vụ quy hoạch xây dựng - Lập, phê duyệt đồ án quyhoạch xây dựng",
  "b. Lập, phê duyệt Nhiệm vụ quy hoạch xây dựng - Điều tra, khảo sát thựcđịa, thu thập bản đồ, tài liệu, số liệu về hiện trạng - Lập, phê duyệt đồ án quyhoạch xây dựng",
  "c. Điều tra, khảo sát thực địa, thu thập bản đồ, tài liệu, số liệu về hiện trạng -Lập, phê duyệt đồ án quy hoạch xây dựng",
  "d. Lập, phê duyệt Nhiệm vụ quy hoạch xây dựng - Điều tra, khảo sát thựcđịa, thu thập bản đồ, tài liệu, số liệu về hiện trạng - Lập đồ án quy hoạch xâydựng - Thẩm định, phê duyệt đồ án quy hoạch xây dựng",
  "d",
  " Quy hoạch xây dựng vùng liên huyện được lập khi nào?",
  "a. Theo đề xuất của Sở Xây dựng phù hợp với quy hoạch vùng, quy hoạchtỉnh",
  "b. Nhằm đáp ứng yêu cầu quản lý, định hướng phát triển, xác định vai tròcủa từng đơn vị hành chính cấp huyện, xã, thị trấn và các đô thị trong tổngthể phát triển chung của vùng liên huyện, đảm bảo phân bổ nguồn lực quốcgia, tỉnh có hiệu quả",
  "c. Đước ủy ban nhân dân cấp tỉnh quyết định",
  "d. Có đầy đủ các cơ sở trên",
  "d",
  " Tỷ lệ bản vẽ hồ sơ đồ án quy hoạch xây dựng vùng liên huyện nàođúng?",
  "a. 1/500.000",
  "b. 1/25.000 - 1/500.000",
  "c. 1/25.000 - 1/100.000",
  "d. 1/50.000 - 1/250.000",
  "d",
  " Các cấp độ đồ án quy hoạch xây dựng khu chức năng ?",
  "a. Quy hoạch chung - Quy hoạch chi tiết (tỷ lệ 1/2.000 và 1/500)",
  "b. Quy hoạch chung - Quy hoạch chi tiết (tỷ lệ 1/5.000, 1/2.000 và 1/500)",
  "c. Quy hoạch chung - Quy hoạch phân khu",
  "d. Quy hoạch chung - Quy hoạch phân khu - Quy hoạch chi tiết",
  "d",
  " Chi phí cho công tác quy hoạch xây được xác định thế nào?",
  "a. Theo hướng dẫn của Bộ Tài chính",
  "b. Theo định mức của Bộ Xây dựng",
  "c. Theo quy định của Cơ quan tổ chức lập quy hoạch",
  "d. Theo định mức của Bộ Xây dựng hoặc Thỏa thuận",
  "b",
  " Những cá nhân nào sau đây bắt buộc phải có chứng chỉ hành nghềtrong hồ sơ năng lực thực hiện một đồ án quy hoạch xây dựng?",
  "a. Chủ nhiệm đồ án và Chủ trì các bộ môn",
  "b. Chủ nhiệm đồ án",
  "c. Chủ trì phần kiến trúc",
  "d. Tất cả các thành viên tham gia thực hiện đồ án quy hoạch xây dựng",
  "a",
  " Căn cứ để lập đồ án quy hoạch xây dựng ?",
  "a. Luật, Nghị định, Thông tư hướng dẫn và các quy chuẩn",
  "b. Hệ thống quy hoạch quốc gia và các quy hoạch có liên quan đã được phêduyệt",
  "c. Nhiệm vụ quy hoạch được duyệt",
  "d. Tất cả các căn cứ trên",
  "d",
  " Cơ quan nào sau đây có thẩm quyền quyết định điều chỉnh cục bộ quyhoạch?",
  "a. Cơ quan tổ chức lập quy hoạch",
  "b. Cơ quan thẩm định quy hoạch",
  "c. Cơ quan tư vấn lập quy hoạch",
  "d. Cơ quan phê duyệt quy hoạch",
  "d",
  " Những cá nhân nào sau đây bắt buộc phải có chứng chỉ hành nghềtrong hồ sơ năng lực thực hiện một dự án thiết kế công trình xâydựng?",
  "a. Chủ nhiệm dự án và Chủ trì các bộ môn",
  "b. Chủ trì phần kiến trúc",
  "c. Chủ trì phần kết cấu",
  "d. Tất cả các thành viên tham gia thực hiện dự án",
  "a",
  " Các lĩnh vực hành nghề kiến trúc sư bao gồm những lĩnh vực nào sauđây?",
  "a. Thiết kế quy hoạch xây dựng;",
  "b. Thiết kế kiến trúc công trình;",
  "c. Thiết kế nội-ngoại thất công trình;",
  "d. Tất cả các lĩnh vực trên.",
  "d",
  " Hoạt động hành nghề kiến trúc sư bao gồm những hoạt động nào?",
  "a. Chủ nhiệm đồ án;",
  "b. Chủ trì thiết kế;",
  "c. Thiết kế viên/Cán bộ thiết kế;",
  "d. Tất cả các công việc trên.",
  "d",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, mật độ xây dựng tối đa củacác lô đất có diện tích tương ứng là 75 m2 ; 200 m2 và 300 m2 là baonhiêu?",
  "a. 90%; 70% và 60%;",
  "b. 80%; 75% và 60%;",
  "c. 80%; 75% và 60%;",
  "d. 95%; 70% và 50%.",
  "a",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, khoảng lùi tối thiểu của côngtrình xây dựng có chiều cao 25m khi tiếp giáp với tuyến đường bộ có lộgiới 23m là bao nhiêu?",
  "a. 0m;",
  "b. 3m;",
  "c. 1m;",
  "d. 5m.",
  "a",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, khoảng lùi tối thiểu của côngtrình xây dựng có chiều cao từ 28m trở lên khi tiếp giáp với tuyếnđường bộ có lộ giới dưới 19m là bao nhiêu?",
  "a. 6m;",
  "b. 3m;",
  "c. 5m;",
  "d. 7m.",
  "a",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, trong đô thị, bán kính phục vụtối đa các trạm phòng, chữa cháy trung tâm là bao nhiêu?",
  "a. <5km;",
  "b. <3km;",
  "c. <1km;",
  "d. <6km.",
  "a",
  " Các trình tự thiết kế xây dựng sau đây, trình tự thiết kế nào là đúng?",
  "a. Thiết kế hai bước và Thiết kế ba bước;",
  "b. Thiết kế ba bước;",
  "c. Thiết kế một bước, Thiết kế hai bước và Thiết kế ba bước;",
  "d. Thiết kế một bước, Thiết kế hai bước, Thiết kế ba bước và Thiết kế theocác bước khác (nếu có).",
  "d",
  " Thiết kế xây dựng bao gồm?",
  "a. Thiết kế sơ bộ và Thiết kế bản vẽ thi công;",
  "b. Thiết kế sơ bộ, Thiết kế cơ sở và Thiết kế bản vẽ thi công;",
  "c. Thiết kế cơ sở và Thiết kế bản vẽ thi công;",
  "d. Thiết kế sơ bộ, Thiết kế cơ sở, Thiết kế bản vẽ thi công và các bước thiếtkế khác (nếu có).",
  "d",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, trong khoảng độ cao 2,5m, đốivới công trình công cộng được xây dựng sát chỉ giới đường đỏ, cánhcửa (trừ cửa thoát nạn) khi mở ra có được vượt quá chỉ giới đường đỏkhông?",
  "a. Không;",
  "b. Được nếu có giấy phép của UBND cấp xã, phường;",
  "c. Được nếu có sự đồng thuận của các hộ dân lân cận;",
  "d. Được.",
  "a",
  " Theo Quy chuẩn QCXDVN 01: 2008/BXD, chức năng đất nhà máy, khotàng trong quy hoạch xây dựng khu công nghiệp được giới hạn nhưthế nào:",
  "a. ≥ 60%",
  "b. ≥ 50%",
  "c. ≥ 55%",
  "d. ≤ 70%",
  "c"];