List<String> list_field_ksxd = ["Trong hoạt động xây dựng có các loại hình khảo sát xây dựng nào?",
"a. Khảo sát địa hình",
"b. Khảo sát địa chất công trình",
"c. Khảo sát địa chất thủy văn",
"d. Bao gồm cả 3 loại hình nêu tại a, b và c",
"d",
" Nhiệm vụ khảo sát xây dựng phải phù hợp với các nội dung nào sauđây?",
"a. Loại và nhóm dự án đầu tư xây dựng",
"b. Nhiệm vụ thiết kế xây dựng công trình",
"c. Loại, cấp công trình xây dựng, loại hình khảo sát và bước thiết kế",
"d. Chủ trương đầu tư xây dựng",
"c",
" Chủ đầu tư không có nghĩa vụ gì trong quá trình khảo sát xây dựng?",
"a. Lựa chọn nhà thầu khảo sát xây dựng, giám sát khảo sát xây dựng trongtrường hợp không tự thực hiện khảo sát xây dựng;",
"b. Cung cấp cho nhà thầu khảo sát xây dựng thông tin, tài liệu có liên quanđến công tác khảo sát;",
"c. Bồi thường thiệt hại khi cung cấp thông tin, tài liệu không phù hợp, vi phạmhợp đồng khảo sát xây dựng;",
"d. Điều chỉnh nhiệm vụ khảo sát xây dựng theo yêu cầu của nhà thầu thiết kế",
"d",
" Thiết kế xây dựng công trình phải đáp ứng các yêu cầu gì?",
"a. Đáp ứng yêu cầu của nhiệm vụ thiết kế; phù hợp với nội dung dự án đầu tưxây dựng được duyệt, quy hoạch xây dựng, cảnh quan kiến trúc, điều kiện tựnhiên, văn hóa - xã hội tại khu vực xây dựng.",
"b. Tuân thủ tiêu chuẩn áp dụng, quy chuẩn kỹ thuật, quy định của pháp luật vềsử dụng vật liệu xây dựng, đáp ứng yêu cầu về công năng sử dụng, côngnghệ áp dụng (nếu có); bảo đảm an toàn chịu lực, an toàn trong sử dụng, mỹquan, bảo vệ môi trường.",
"c. Có giải pháp thiết kế phù hợp và chi phí xây dựng hợp lý; bảo đảm đồng bộtrong từng công trình và với các công trình liên quan;",
"d. Cả 3 yêu cầu nêu tại A, B và C",
"d",
" Thiết kế xây dựng triển khai sau thiết kế cơ sở gồm những nội dung chủyếu gì?",
"a. Phương án kiến trúc, phương án công nghệ (nếu có)",
"b. Phương án kết cấu, loại vật liệu chủ yếu",
"c. Chỉ dẫn kỹ thuật",
"d. Bao gồm cả 3 nội dung nêu tại a, b và c",
"d",
" Đối với dự án sử dụng vốn ngân sách nhà nước, ai là người phê duyệtthiết kế bản vẽ thi công và dự toán xây dựng trong trường hợp thiết kế 2bước?",
"a. Người có thẩm quyền quyết định đầu tư",
"b. Chủ đầu tư",
"c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khu vực",
"d. Cơ quan chuyên môn của người quyết định đầu tư",
"a",
" Đối với dự án sử dụng vốn nhà nước ngoài ngân sách, ai là người phêduyệt thiết kế bản vẽ thi công và dự toán xây dựng, trong trường hợpthiết kế 2 bước",
"a. Người quyết định đầu tư",
"b. Chủ đầu tư",
"c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khu vực",
"d. Cơ quan chuyên môn của người quyết định đầu tư",
"b",
" Trường hợp dự án chỉ yêu cầu lập Báo cáo kinh tế kỹ thuật đầu tư xâydựng thì ai là người phê duyệt thiết kế bản vẽ thi công, dự toán xâydựng công trình?",
"a. Người quyết định đầu tư.",
"b. Chủ đầu tư.",
"c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khu vực",
"d. Cơ quan chuyên môn của người quyết định đầu tư",
"a",
" Tổ chức nào không được thực hiện thẩm tra thiết kế, dự toán công trìnhX?",
"a. Tổ chức đã thiết kế xây dựng công trình X.",
"b. Cơ quan chuyên môn về xây dựng.",
"c. Ban quản lý dự án đầu tư xây dựng thuộc chủ đầu tư",
"d. Tổ chức tư vấn giám sát thi công xây dựng công trình X.",
"a",
" Thiết kế xây dựng công trình không được thay đổi khi nào?",
"a. Khi điều chỉnh dự án đầu tư xây dựng có yêu cầu thay đổi thiết kế cơ sở.",
"b. Trong quá trình thi công xây dựng, phát hiện yếu tố bất hợp lý nếu khôngthay đổi sẽ ảnh hưởng tới chất lượng công trình xây dựng.",
"c. Khi điều chỉnh tổng mức đầu tư của dự án do chỉ số giá xây dựng tăng sovới chỉ số giá xây dựng lập dự phòng cho yếu tố trượt giá.",
"d. Khi thiết kế bước trước đã được phê duyệt có thay đổi.",
"c",
" Đối với trường hợp thiết kế 1 bước thì thiết kế bản vẽ thi công được lậptrên cơ sở nào?",
"a. Nhiệm vụ thiết kế được chủ đầu tư phê duyệt.",
"b. Nhiệm vụ thiết kế được người có thẩm quyền quyết định đầu tư phê duyệt.",
"c. Phương án thiết kế do nhà thầu tư vấn thiết kế đề xuất.",
"d. Cả 3 đáp án a, b và c đều không đúng.",
"a",
" Theo phân cấp công trình, kho chứa vật liệu nổ thuộc cấp đặc biệt củadự án sản xuất thuốc nổ, theo quy định tại Nghị định 59/2015/NĐ-CP thìcơ quan chuyên môn về xây dựng trực thuộc Bộ Công thương thẩmđịnh thiết kế, dự toán xây dựng công trình này, vậy những công trìnhcòn lại của dự án này thì cơ quan nào thẩm định?",
"a. Cơ quan chuyên môn về xây dựng thuộc Bộ Công thương",
"b. Cơ quan chuyên môn về xây dựng thuộc Bộ Xây dựng",
"c. Cơ quan chuyên môn của người quyết định đầu tư",
"d. Sở quản lý công trình xây dựng chuyên ngành nơi xây dựng các công trình",
"a",
" Trường hợp nào khi điều chỉnh thiết kế phải trình cơ quan chuyên mônvề xây dựng thẩm định lại?",
"a. Thay đổi tải trọng thiết kế",
"b. Thay đổi vật liệu sử dụng cho công trình",
"c. Thay đổi biện pháp tổ chức thi công",
"d. Bao gồm cả 3 trường hợp a, b và c",
"a",
" Chỉ dẫn kỹ thuật được phê duyệt cùng với phê duyệt thiết kế, dự toánhay phê duyệt riêng?",
"a. Phê duyệt riêng với phê duyệt thiết kế",
"b. Phê duyệt cùng với khi phê duyệt thiết kế",
"c. Do người có thẩm quyền phê duyệt quyết định",
"d. Chỉ dẫn kỹ thuật không phải phê duyệt",
"c",
" Trước khi trình cơ quan chuyên môn về xây dựng thẩm định thiết kế,chủ đầu tư có cần phải thuê tư vấn thẩm tra hay không?",
"a. Có",
"b. Không",
"c. Do chủ đầu tư quyết định",
"d. Có, nhưng theo yêu cầu của cơ quan chuyên môn về xây dựng",
"d",
" Nhà ở riêng lẻ có quy mô thế nào thì do chủ đầu tư tự tổ chức thiết kế vàchịu trách nhiệm về an toàn công trình và công trình lân cận?",
"a. Dưới 3 tầng (gồm cả tầng trệt) hoặc có chiều cao dưới 12 m tính từ cốt 0.00",
"b. Dưới 250 m2 sàn xây dựng",
"c. Đáp án a hoặc b",
"d. Bao gồm cả đáp án a và b",
"d",
" Thiết kế kỹ thuật, dự toán xây dựng công trình thuộc dự án sử dụng vốnngân sách nhà nước đã được cơ quan chuyên môn về xây dựng thẩmđịnh. Trong trường hợp, khi thi công xây dựng phát sinh điều chỉnh khốilượng nhưng không ảnh hưởng tới an toàn công trình thì phải trình cơquan nào thẩm định lại trước khi phê duyệt điều chỉnh?",
"a. Người quyết định đầu tư",
"b. Chủ đầu tư",
"c. Cơ quan chuyên môn về xây dựng",
"d. Ban quản lý dự án",
"a",
" Cá nhân có trình độ cao đẳng, trung cấp đã được cấp chứng chỉ hànhnghề thiết kế, được chủ trì thiết kế công trình cấp mấy?",
"a. Cấp II trở xuống.",
"b. Cấp III trở xuống.",
"c. Cấp IV.",
"d. Không được chủ trì thiết kế xây dựng",
"b",
" Chủ đầu tư không có quyền nào dưới đây?",
"a. Tự thực hiện khảo sát xây dựng khi có đủ điều kiện năng lực;",
"b. Phê duyệt nhiệm vụ khảo sát xây dựng, phương án kỹ thuật khảo sát do tưvấn thiết kế hoặc do nhà thầu khảo sát lập;",
"c. Điều chỉnh nhiệm vụ khảo sát xây dựng theo yêu cầu hợp lý của tư vấn thiếtkế xây dựng;",
"d. Yêu cầu tư vấn khảo sát sử dụng kết quả khảo sát của dự án liền kề.",
"d",
" Chủ đầu tư không có trách nhiệm nào dưới đây?",
"a. Lựa chọn nhà thầu khảo sát xây dựng, giám sát khảo sát xây dựng trongtrường hợp không tự thực hiện khảo sát xây dựng, giám sát khảo sát xâydựng",
"b. Cung cấp cho nhà thầu khảo sát xây dựng thông tin, tài liệu có liên quanđến công tác khảo sát",
"c. Trình cơ quan chuyên môn về xây dựng thẩm định phương án kỹ thuật vàdự toán cho công tác khảo sát xây dựng",
"d. Tổ chức giám sát công tác khảo sát xây dựng; nghiệm thu, phê duyệt kếtquả khảo sát theo quy định của pháp luật",
"c",
" Nhà thầu khảo sát xây dựng có quyền nào dưới đây?",
"a. Yêu cầu chủ đầu tư và các bên có liên quan cung cấp số liệu, thông tin liênquan theo quy định của hợp đồng để thực hiện khảo sát xây dựng",
"b. Từ chối thực hiện yêu cầu ngoài hợp đồng khảo sát xây dựng",
"c. Thuê nhà thầu phụ thực hiện khảo sát xây dựng theo quy định của hợpđồng khảo sát xây dựng",
"d. Cả 3 phương án trên đều đúng",
"d",
" Nhà thầu khảo sát có nghĩa vụ gì?",
"a. Thực hiện đúng yêu cầu khảo sát xây dựng theo quy định của pháp luật vềxây dựng và hợp đồng khảo sát xây dựng;",
"b. Không phải đề xuất, bổ sung nhiệm vụ khảo sát xây dựng khi phát hiện yếutố ảnh hưởng trực tiếp đến giải pháp thiết kế;",
"c. Không chịu trách nhiệm về quản lý chất lượng khảo sát của nhà thầu phụ(nếu có) và kết quả khảo sát của nhà thầu phụ.",
"d. Cả 3 phương án trên đều đúng",
"a",
" Thiết kế xây dựng nhà ở riêng lẻ phải đáp ứng các yêu cầu nào?",
"a. Tuân thủ tiêu chuẩn áp dụng, quy chuẩn kỹ thuật",
"b. Quy định của pháp luật về sử dụng vật liệu xây dựng",
"c. Bảo đảm an toàn chịu lực, an toàn trong sử dụng",
"d. Đáp ứng tất cả các yêu cầu nêu tại a, b và c",
"d",
" Trường hợp nào khi xây dựng nhà ở riêng lẻ, hộ gia đình không được tựtổ chức thiết kế xây dựng?",
"a. Nhà ở có tổng diện tích sàn xây dựng nhỏ hơn 250 m2",
"b. Nhà ở có chiều cao dưới 3 tầng",
"c. Nhà ở dưới 3 tầng nhưng có chiều cao trên 12 mét.",
"d. Cả 3 trường hợp a, b và c",
"c",
" Người nào có thẩm quyền quyết định việc thi tuyển hoặc tuyển chọnphương án thiết kế kiến trúc công trình xây dựng?",
"a. Cơ quan quản lý quy hoạch kiến trúc của địa phương",
"b. Cơ quan chuyên môn về xây dựng theo phân cấp",
"c. Người có thẩm quyền quyết định đầu tư",
"d. Chủ đầu tư",
"c",
" Dự án đầu tư xây dựng bệnh viện nhóm A sử dụng vốn ngân sách nhànước, có công trình cấp cao nhất là cấp II do Chủ tịch UBND cấp tỉnhquyết định đầu tư thì phải trình cơ quan nào thẩm định thiết kế kỹ thuật,dự toán xây dựng?",
"a. Cơ quan chuyên môn về xây dựng của Bộ Xây dựng",
"b. Sở Xây dựng",
"c. Cơ quan chuyên môn của người quyết định đầu tư",
"d. Cả 3 phương án a, b và c đều sai",
"b",
" Dự án đầu tư xây dựng bệnh viện nhóm B sử dụng vốn ngân sách nhànước, cócông trình cấp cao nhất là cấp I do Chủ tịch UBND cấp tỉnh quyết địnhđầu tư thì phải trình cơ quan nào thẩm định thiết kế kỹ thuật, dự toán xâydựng?",
"a. Cơ quan chuyên môn về xây dựng của Bộ Xây dựng",
"b. Sở Xây dựng",
"c. Cơ quan chuyên môn của người quyết định đầu tư",
"d. Cả 3 phương án A, B và C đều sai",
"a",
" Dự án đầu tư xây dựng bệnh viện nhóm A sử dụng vốn nhà nước ngoàingân sách, có công trình cấp cao nhất là cấp II do Chủ tịch UBND cấptỉnh quyết định đầu tư thì phải trình cơ quan nào thẩm định thiết kế cơsở?",
"a. Cơ quan chuyên môn về xây dựng của Bộ Xây dựng",
"b. Sở Xây dựng",
"c. Sở Kế hoạch và đầu tư",
"d. Cơ quan chuyên môn của người quyết định đầu tư",
"a",
" Chủ đầu tư có quyền gì trong công tác thiết kế xây dựng?",
"a. Không được tự thực hiện thiết kế xây dựng mặc dù có đủ điều kiện nănglực hoạt động theo quy định",
"b. Không được yêu cầu nhà thầu thiết kế xây dựng sửa đổi, bổ sung thiết kếhoặc lựa chọn nhà thầu thiết kế khác thực hiện sửa đổi, bổ sung, thay đổi thiếtkế trong trường hợp nhà thầu thiết kế ban đầu từ chối thực hiện công việc này",
"c. Đình chỉ thực hiện hoặc chấm dứt hợp đồng thiết kế xây dựng theo quyđịnh của hợp đồng và quy định của pháp luật có liên quan",
"d. Không được giám sát thực hiện hợp đồng thiết kế đã ký kết với nhà thầu",
"c",
" Chủ đầu tư không có trách nhiệm gì trong công tác thiết kế xây dựng?",
"a. Lựa chọn nhà thầu thiết kế xây dựng trong trường hợp không tự thựchiện thiết kế xây dựng;",
"b. Xác định nhiệm vụ thiết kế xây dựng;",
"c. Cung cấp thông tin, tài liệu cho nhà thầu thiết kế xây dựng;",
"d. Bồi thường thiệt hại khi nhà thầu thiết kế áp dụng quy chuẩn, tiêu chuẩnkhông đúng quy định",
"d"];