List<String> list_quest_All = [" Các hoạt động đầu tư xây dựng chịu sự điều chỉnh của pháp luật nào dưới đây?",
  "a. Pháp luật về xây dựng",
  "b. Pháp luật về xây dựng và pháp luật về đầu tư công",
  "c. Pháp luật về xây dựng và pháp luật về đấu thầu",
  "d. Pháp luật về xây dựng và pháp luật khác có liên quan",
  "d",
  "Theo quy định của pháp luật về xây dựng, hoạt động xây dựng gồm cáccông việc nào dưới đây?",
  "a. Lập quy hoạch xây dựng, lập dự án đầu tư xây dựng công trình, khảo sátxây dựng",
  "b. Thiết kế xây dựng, thi công xây dựng, giám sát xây dựng, quản lý dự án,lựa chọn nhà thầu, nghiệm thu, bàn giao đưa công trình vào khai thác sử dụng",
  "c. Bảo hành, bảo trì công trình xây dựng và hoạt động khác có liên quan đếnxây dựng công trình",
  "d. Các công việc nêu tại điểm a, b và c",
  "d",
  "Dự án đầu tư xây dựng sử dụng vốn ODA thì thực hiện theo quy địnhnào?",
  "a. Theo quy định của Hiệp định vay vốn mà Việt Nam ký kết với tổ chức chovay",
  "b. Theo pháp luật về xây dựng",
  "c. Theo quy định của Hiệp định vay vốn mà Việt Nam ký kết với tổ chức chovay, các quy định của pháp luật về xây dựng và pháp luật khác liên quan",
  "d. Theo quy định của Hiệp định vay vốn mà Việt Nam ký kết với tổ chức chovay và các quy định của pháp luật về xây dựng",
  "c",
  "Việc áp dụng tiêu chuẩn, quy chuẩn kỹ thuật trong hoạt động đầu tư xâydựng phải tuân thủ theo những nguyên tắc nào?",
  "a. Tuân thủ Quy chuẩn kỹ thuật quốc gia",
  "b. Tiêu chuẩn được viện dẫn trong quy chuẩn kỹ thuật hoặc văn bản quyphạm pháp luật khác có liên quan",
  "c. Tiêu chuẩn được áp dụng trong hoạt động đầu tư xây dựng theo nguyên tắctự nguyện",
  "d. Tất cả các quy định tại a, b và c",
  "d",
  "Việc giám sát đánh giá đầu tư đối với các dự án đầu tư xây dựng sửdụng vốn nhà nước căn cứ vào các quy định nào?",
  "a. Pháp luật về xây dựng",
  "b. Pháp luật về đầu tư công",
  "c. Pháp luật về đầu tư công và pháp luật về xây dựng",
  "d. Pháp luật về đầu tư công, pháp luật về xây dựng và pháp luật khác có liênquan",
  "d",
  "Những chủ thể nào bắt buộc phải mua bảo hiểm công trình trong thờigian thi công xây dựng đối với công trình có ảnh hưởng đến an toàncộng đồng, môi trường, công trình có yêu cầu kỹ thuật đặc thù, điều kiệnthi công xây dựng phức tạp ?",
  "a. Chủ đầu tư xây dựng công trình",
  "b. Nhà thầu thi công xây dựng công trình",
  "c. Nhà thầu tư vấn thiết kế xây dựng công trình",
  "d. Cả 3 chủ thể nêu tại a, b và c",
  "a",
  "Những chủ thể nào bắt buộc phải mua bảo hiểm trách nhiệm nghềnghiệp trong hoạt động đầu tư xây dựng?",
  "a. Nhà thầu khảo sát xây dựng",
  "b. Nhà thầu tư vấn thiết kế xây dựng công trình",
  "c. Nhà thầu khảo sát xây dựng và Nhà thầu tư vấn thiết kế xây dựng côngtrình",
  "d. Chủ đầu tư xây dựng công trình và Nhà thầu khảo sát xây dựng",
  "c",
  "Dự án đầu tư xây dựng được phân thành loại và nhóm A, B, C đối vớicác nguồn vốn nào?",
  "a. Nguồn vốn ngân sách nhà nước",
  "b. Nguồn vốn nhà nước ngoài ngân sách",
  "c. Nguồn vốn khác không phải nguồn vốn nêu tại điểm a và b",
  "d. Tất cả các nguồn vốn nêu tại điểm a, b và c.",
  "d",
  "Theo quy định của pháp luật hiện hành về xây dựng, vốn nhà nướcngoài ngân sách bao gồm:",
  "a. Vốn ODA, vốn vay ưu đãi của Nhà nước, vốn do Nhà nước bảo lãnh vay",
  "b. Vốn phát triển của doanh nghiệp nhà nước, vốn góp tiền sử dụng đất củaDoanh nghiệp nhà nước",
  "c. Các dự án PPP",
  "d. Các trường hợp trên",
  "d",
  " Theo quy định của pháp luật về xây dựng, những công tác gì được liệtkê dưới đây thuộc giai đoạn chuẩn bị đầu tư xây dựng ?",
  "a. Xin chủ trương đầu tư xây dựng",
  "b. Lập, thẩm định, phê duyệt Báo cáo nghiên cứu khả thi đầu tư xây dựng",
  "c. Xin phép xây dựng",
  "d. Bao gồm công tác a và b",
  "d",
  " Theo quy định của pháp luật về xây dựng, công tác nào sau đây ở giaiđoạn thực hiện đầu tư xây dựng?",
  "a. Tổ chức lựa chọn nhà thầu, tổng thầu xây dựng để thực hiện các bước thiếtkế bản vẽ thi công, thi công xây dựng công trình",
  "b. Thiết kế bản vẽ thi công và dự toán xây dựng",
  "c. Lựa chọn nhà thầu giám sát thi công xây dựng",
  "d. Tất cả các công tác trên",
  "d",
  " Theo quy định của pháp luật về xây dựng, công trình xây dựng đượcphân cấp trên cơ sở các căn cứ nào?",
  "a. Quy mô, tầm quan trọng áp dụng cho từng loại công trình",
  "b. Thời hạn sử dụng, vật liệu",
  "c. Yêu cầu kỹ thuật xây dựng công trình",
  "d. Tất cả các căn cứ trên",
  "d",
  " Việc phân loại công trình xây dựng theo quy định của pháp luật về xâydựng trên cơ sở tiêu chí nào?",
  "a. Theo công năng sử dụng",
  "b. Theo kiến trúc công trình",
  "c. Do người quyết định đầu tư quy định",
  "d. Do chủ đầu tư quy định",
  "a",
  " Những dự án đầu tư xây dựng nhóm nào có thể được phân chia thànhcác dự án thành phần hoặc phân kỳ đầu tư để quản lý thực hiện như mộtdự án độc lập?",
  "a. Dự án quan trọng quốc gia, dự án nhóm A",
  "b. Dự án chỉ yêu cầu lập Báo cáo kinh tế kỹ thuật",
  "c. Dự án nhóm B, C",
  "d. Cả 3 phương án a, b và c",
  "a",
  " Dự án đầu tư xây dựng phải đáp ứng các yêu cầu nào dưới đây?",
  "a. Phù hợp với quy hoạch",
  "b. Có phương án công nghệ và phương án thiết kế xây dựng phù hợp",
  "c. Bảo đảm chất lượng, an toàn trong xây dựng và bảo vệ môi trường",
  "d. Cả 3 phương án trên",
  "d",
  " Các dự án đầu tư xây dựng có quy mô nhóm nào yêu cầu phải lập Báocáo nghiên cứu tiền khả thi để trình cấp có thẩm quyền cho phép đầu tưhoặc chấp thuận chủ trương đầu tư?",
  "a. Dự án quan trọng quốc gia",
  "b. Dự án nhóm A",
  "c. Dự án quan trọng quốc gia và dự án nhóm A",
  "d. Dự án quan trọng quốc gia, dự án nhóm A, nhóm B và nhóm C",
  "c",
  " Dự án đầu tư xây dựng có tổng mức đầu tư bao nhiêu (Trừ công trìnhxây dựng sử dụng cho mục đích tôn giáo) thì Chủ đầu tư phải lập Báocáo nghiên cứu khả thi đầu tư xây dựng?",
  "a. Từ 45 tỷ đồng trở lên",
  "b. Từ 15 tỷ đồng trở lên",
  "c. Từ 7 tỷ đồng trở lên",
  "d. Từ 80 tỷ trở lên",
  "b",
  " Khi thẩm định dự án đầu tư xây dựng sử dụng vốn nhà nước ngoài ngânsách, cơ quan chuyên môn về xây dựng phải thẩm định những nội dungnào dưới đây?",
  "a. Nội dung khác của báo cáo nghiên cứu khả thi đầu tư xây dựng",
  "b. Thiết kế cơ sở phần xây dựng của báo cáo nghiên cứu khả thi đầu tư xâydựng",
  "c. Thiết kế công nghệ của báo cáo nghiên cứu khả thi đầu tư xây dựng",
  "d. Tất cả các nội dung tại a, b và c",
  "b",
  " Cơ quan nào chủ trì tổ chức thẩm định dự án đầu tư xây dựng (khôngthuộc diện dự án quan trọng quốc gia) sử dụng vốn ngân sách nhànước?",
  "a. Cơ quan chuyên môn về xây dựng theo phân cấp",
  "b. Cơ quan chuyên môn trực thuộc người quyết định đầu tư",
  "c. Cả phương án a và b",
  "d. Chủ đầu tư xây dựng công trình",
  "a",
  " Đối với dự án sử dụng vốn nhà nước ngoài ngân sách thì cơ quan nàochủ trì thẩm định thiết kế công nghệ và các nội dung khác của Báo cáonghiên cứu khả thi đầu tư xây dựng?",
  "a. Sở Xây dựng",
  "b. Cơ quan chuyên môn trực thuộc người quyết định đầu tư",
  "c. Chủ đầu tư xây dựng",
  "d. Văn phòng UBND tỉnh",
  "b",
  " Dự án đầu tư xây dựng nào dưới đây không bắt buộc phải lập báo cáonghiên cứu khả thi mà chỉ cần lập Báo cáo kinh tế - kỹ thuật?",
  "a. Dự án đầu tư xây dựng công trình tôn giáo và nhà ở riêng lẻ của hộ giađình",
  "b. Dự án đầu tư xây dựng công trình tôn giáo và dự án đầu tư xây dựng cótổng mức đầu tư dưới 15 tỷ đồng (không tính tiền sử dụng đất)",
  "c. Cả trường hợp a và b",
  "d. Các trường hợp a, b và c đều không đúng",
  "b",
  " Đối với dự án đầu tư xây dựng không sử dụng vốn nhà nước thì cơquan chuyên môn về xây dựng thuộc các Bộ quản lý công trình xâydựng chuyên ngành thẩm định những nội dung nào của dự án?",
  "a. Tất cả các nội dung của dự án",
  "b. Thiết kế cơ sở của dự án đối với công trình cấp 1, cấp đặc biệt",
  "c. Thiết kế cơ sở của dự án quan trọng quốc gia và dự án nhóm A",
  "d. Thiết kế cơ sở và thiết kế công nghệ của dự án",
  "b",
  " Khi thẩm định thiết kế cơ sở của dự án đầu tư xây dựng yêu cầu phảixem xét đánh giá những nội dung gì?",
  "a. Sự phù hợp của thiết kế với quy hoạch chi tiết xây dựng",
  "b. Sự phù hợp của các giải pháp thiết kế về bảo đảm an toàn xây dựng, môitrường, phòng chống cháy nổ",
  "c. Bao gồm cả a và b",
  "d. Bao gồm cả a, b và đánh giá đảm bảo tính khả thi của dự án",
  "c",
  " Trong các nội dung thẩm định dự án không bao gồm nội dung nào dướiđây?",
  "a. Xem xét các yếu tố bảo đảm tính hiệu quả và tính khả thi của dự án",
  "b. Xem xét việc xác định tổng mức đầu tư của dự án",
  "c. Xem xét việc xác định dự toán các công trình của dự án",
  "d. Xem xét sự hợp lý của thiết kế cơ sở",
  "c",
  " Hợp đồng trong hoạt động xây dựng theo hình thức giá có những loạinào?",
  "a. Hình thức trọn gói, hình thức theo thời gian",
  "b. Hình thức điều chỉnh giá, Hình thức theo đơn giá cố định",
  "c. Bao gồm các hình thức nêu tại a và b",
  "d. Không có hình thức nào nêu tại a và b",
  "c",
  " Chức năng, nhiệm vụ của Ban QLDA chuyên ngành, ban QLDA khu vựcdo ai quy định?",
  "a. Người có thẩm quyền quyết định đầu tư",
  "b. Người có thẩm quyền quyết định thành lập Ban QLDA chuyên ngành, banQLDA khu vực",
  "c. Cơ quan chuyên môn về xây dựng",
  "d. Chủ đầu tư",
  "b",
  " Đối với dự án đầu tư xây dựng chỉ yêu cầu lập Báo cáo kinh tế kỹ thuậtđầu tư xây dựng thì chủ thể nào phê duyệt thiết kế bản vẽ thi công?",
  "a. Người có thẩm quyền quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Ban quản lý dự án đầu tư xây dựng",
  "d. Cơ quan chuyên môn về xây dựng",
  "a",
  " Chủ thể nào phải chịu trách nhiệm chính về an toàn lao động trên côngtrường?",
  "a. Chủ đầu tư",
  "b. Nhà thầu thi công xây dựng công trình",
  "c. Nhà thầu tư vấn giám sát thi công xây dựng công trình",
  "d. Cả a, b và c",
  "b",
  " Các dự án đầu tư xây dựng thuộc Tập đoàn kinh tế, Tổng công ty nhànước phải tuân thủ theo các quy định nào?",
  "a. Điều lệ, quy chế hoạt động của Tập đoàn, Tổng công ty",
  "b. Theo quy định Pháp luật về xây dựng, pháp luật về đấu thầu và pháp luậtkhác liên quan",
  "c. Bao gồm b và c",
  "d. Chỉ tuân thủ quy định của pháp luật về xây dựng",
  "c",
  " Theo quy định của pháp luật về xây dựng, dự án đầu tư xây dựng sửdụng vốn nhà nước có tổng mức đầu tư bao nhiêu thì không phải thànhlập ban QLDA mà sử dụng bộ máy chuyên môn của chủ đầu tư để kiêmnhiệm quản lý dự án?",
  "a. Dưới 15 tỷ đồng",
  "b. Dưới 7 tỷ đồng",
  "c. Dưới 10 tỷ đồng",
  "d. Không có dự án nào",
  "a",
  " Theo quy định của pháp luật về xây dựng, đối với các gói thầu sử dụngvốn nhà nước thì hợp đồng xây dựng được ký kết vào thời điểm nào?",
  "a. Sau khi hoàn thành việc lựa chọn nhà thầu",
  "b. Sau khi hoàn thành việc lựa chọn nhà thầu và kết thúc đàm phán hợp đồng",
  "c. Trước khi khởi công xây dựng công trình",
  "d. Cả 3 phương án a, b và c",
  "b",
  " Theo quy định của pháp luật về xây dựng, đối với các gói thầu sử dụngvốn nhà nước thì hợp đồng xây dựng được ký kết giữa bên giao thầu vàbên nhận thầu bằng hình thức nào?",
  "a. Bằng văn bản thỏa thuận giữa bên giao thầu và bên nhận thầu để thực hiệnmột phần công việc trong hoạt động đầu tư xây dựng.",
  "b. Bằng văn bản thỏa thuận giữa bên giao thầu và bên nhận thầu để thực hiệntoàn bộ công việc trong hoạt động đầu tư xây dựng.",
  "c. Phương án a hoặc b",
  "d. Cả 2 phương án a và b",
  "c",
  " Theo quy định của pháp luật về xây dựng, đối với các gói thầu sử dụngvốn nhà nước, trường hợp bên nhận thầu là liên danh các nhà thầu thìkhi ký kết hợp đồng xây dựng với bên giao thầu những nhà thầu nàotrong liên danh phải cử đại diện hợp pháp của mình để ký hợp đồng?",
  "a. Nhà thầu được liên danh các nhà thầu cử làm đại diện cho liên danh",
  "b. Tất cả các nhà thầu tham gia trong liên danh",
  "c. Phương án a hoặc b",
  "d. Bất kể nhà thầu nào trong liên danh theo yêu cầu của bên giao thầu",
  "c",
  " Theo quy định của pháp luật về xây dựng, đối với các gói thầu sử dụngvốn nhà nước thì hiệu lực của hợp đồng xây dựng được tính từ thờiđiểm nào?",
  "a. Từ ngày ký kết hợp đồng",
  "b. Từ ngày bên giao thầu nhận được bảo đảm thực hiện hợp đồng của bênnhận thầu",
  "c. Từ ngày do bên giao thầu và bên nhận thầu thỏa thuận trong hợp đồng.",
  "d. Bao gồm cả a, b và c",
  "c",
  " Đối với các gói thầu sử dụng vốn nhà nước, việc điều chỉnh giá hợpđồng chỉ được áp dụng đối với loại hợp đồng nào?",
  "a. Hợp đồng theo đơn giá cố định; hợp đồng theo thời gian",
  "b. Hợp đồng theo đơn giá điều chỉnh, hợp đồng theo thời gian",
  "c. Cả a và b",
  "d. a hoặc b",
  "b",
  " Đối với các gói thầu sử dụng vốn nhà nước, nếu khối lượng công việcphát sinh lớn hơn 20% khối lượng công việc tương ứng ghi trong hợpđồng hoặc khối lượng phát sinh chưa có đơn giá trong hợp đồng thìđơn giá được áp dụng để điều chỉnh giá hợp đồng được tính thế nào?",
  "a. Do bên nhận thầu và bên giao thầu thống nhất đơn giá mới theo nguyên tắcthỏa thuận",
  "b. Lấy đơn giá trong hợp đồng đã ký kết giữa bên nhận thầu và bên giao thầu",
  "c. Lấy đơn giá mới theo đề xuất của bên giao thầu",
  "d. Cả 3 phương án a, b và c đều không đúng",
  "a",
  " Đối với các gói thầu thi công xây dựng sử dụng vốn nhà nước, tiến độthực hiện hợp đồng được điều chỉnh trong các trường hợp nào?",
  "a. Trong quá trình thực hiện hợp đồng xảy ra các trường hợp bất khả kháng",
  "b. Do bên giao thầu thay đổi thiết kế hoặc bàn giao mặt bằng không đúng vớithỏa thuận trong hợp đồng",
  "c. Do nhà thầu thực hiện không tuân thủ các biện thi công đễ xảy ra sự cốphải tạm dừng thi công để xử lý sự cố",
  "d. Cả 3 trường hợp trên",
  "d",
  " Hợp đồng EPC là loại hợp đồng thực hiện những công việc gì?",
  "a. Thiết kế và thi công xây dựng",
  "b. Thiết kế và cung cấp vật tư, thiết bị",
  "c. Thiết kế, cung cấp vật tư, thiết bị và thi công xây dựng",
  "d. Lập dự án, thiết kế, cung cấp vật tư, thiết bị và thi công xây dựng",
  "c",
  " Đối với hợp đồng tổng thầu EPC ngoài tiến độ thi công cho từng giaiđoạn của tổng thầu, nhà thầu còn phải lập tiến độ thực hiện cho nhữngcông việc nào dưới đây?",
  "a. Tiến độ cho công việc thiết kế",
  "b. Tiến độ cho công việc cung cấp thiết bị và thi công xây dựng",
  "c. Tiến độ cho công việc thiết kế và thi công xây dựng",
  "d. Tiến độ cho công việc thiết kế, cung cấp vật tư thiết bị và thi công xây dựng",
  "d",
  " Đối với các gói thầu sử dụng vốn nhà nước, nhà thầu chính có quyềngiao 100% công việc của hợp đồng đã ký kết với bên giao thầu cho nhàthầu phụ không?",
  "a. Có",
  "b. Không",
  "c. Tùy thuộc vào tình hình cụ thể và nhà thầu chính quyết định",
  "d. Do bên giao thầu và bên nhận thầu thỏa thuận",
  "b",
  " Theo quy định của pháp luật Xây dựng hiện hành, nhà thầu nào có tráchnhiệm lập biện pháp an toàn cho người và thiết bị thi công công trìnhtrên công trường xây dựng?",
  "a. Nhà thầu thiết kế",
  "b. Nhà thầu thi công xây dựng",
  "c. Chủ đầu tư",
  "d. Tư vấn giám sát thi công xây dựng",
  "b",
  " Hồ sơ trình thẩm định, phê duyệt dự án đầu tư xây dựng không bao gồmtài liệu nào dưới đây?",
  "a. Tờ trình thẩm định, phê duyệt dự án",
  "b. Thiết kế cơ sở của dự án",
  "c. Thiết kế kỹ thuật của dự án",
  "d. Giấy tờ liên quan đến đất đai",
  "c",
  " Công tác nào sau đây không nằm trong giai đoạn thực hiện dự án đầu tưxây dựng?",
  "a. Thẩm định, phê duyệt thiết kế bản vẽ thi công và dự toán",
  "b. Lựa chọn nhà thầu thi công xây dựng",
  "c. Thẩm định, phê duyệt dự án",
  "d. Thẩm định, phê duyệt quyết toán vốn đầu tư xây dựng",
  "c",
  " Các ban quản lý dự án đầu tư xây dựng chuyên ngành, ban quản lý dựán đầu tư xây dựng khu vực do các Bộ trưởng, Thủ trưởng cơ quanngang bộ, Chủ tịch UBND cấp tỉnh, cấp huyện thành lập có được thuê tổchức tư vấn có đủ điều kiện năng lực để thực hiện một số phần việctrong quá trình quản lý thực hiện dự án không?",
  "a. Có",
  "b. Không",
  "c. Có nhưng phải được chủ đầu tư chấp thuận",
  "d. Có nhưng phải được người quyết định đầu tư chấp thuận",
  "d",
  " Trường hợp thuê tư vấn quản lý dự án thì nhiệm vụ, quyền hạn của tưvấn QLDA do ai quyết định?",
  "a. Do chủ đầu tư thông qua hợp đồng",
  "b. Do pháp luật quy định",
  "c. Do người quyết định đầu tư",
  "d. Cấp trên của tổ chức tư vấn quản lý dự án",
  "a",
  " Theo quy định của pháp luật xây dựng hiện hành, hợp đồng xây dựngkhông có hình thức nào dưới đây?",
  "a. Hợp đồng theo giá trọn gói",
  "b. Hợp đồng theo tỷ lệ %",
  "c. Hợp đồng theo đơn giá điều chỉnh",
  "d. Hợp đồng theo đơn giá cố định",
  "b",
  " Trong quá trình thực hiện hợp đồng, bên nhận thầu có được thay đổingười đại diện quản lý thực hiện hợp đồng không?",
  "a. Có",
  "b. Không",
  "c. Có nhưng phải được sự chấp thuận của bên giao thầu",
  "d. Cả a, b và c đều không đúng",
  "c",
  " Theo quy định của pháp luật về xây dựng, việc tranh chấp hợp đồng xâydựng được giải quyết thế nào?",
  "a. Các bên thống nhất thương lượng để giải quyết",
  "b. Trường hợp các bên không thương lượng được với nhau thì đề nghị ra Tòaán nhân dân địa phương nơi xây dựng công trình",
  "c. Các bên thống nhất thương lượng để giải quyết. Trường hợp các bênkhông thương lượng được với nhau thì đề nghị ra Tòa án nhân dân địaphương nơi xây dựng công trình",
  "d. Các bên thống nhất thương lượng để giải quyết. Trường hợp các bênkhông thương lượng được với nhau thì việc đưa ra Tòa án nào để giải quyếtlà do Bên giao thầu quyết định",
  "c",
  " Những cá nhân nào dưới đây không bắt buộc phải có chứng chỉ hànhnghề hoạt động xây dựng?",
  "a. Chủ nhiệm thiết kế xây dựng công trình",
  "b. Chủ trì thiết kế bộ môn trong công trình xây dựng",
  "c. Cá nhân giám sát thi công của nhà thầu thi công xây dựng",
  "d. Tư vấn giám sát thi công xây dựng",
  "c",
  " Chủ nhiệm thiết kế xây dựng hạng I phải đáp ứng các điều kiện gì?",
  "a. Có trình độ đại học thuộc chuyên ngành phù hợp",
  "b. Có thời gian làm công tác thiết kế xây dựng tối thiểu 7 năm",
  "c. Đã làm chủ nhiệm thiết kế phần việc thuộc lĩnh vực phù hợp ít nhất 01 côngtrình từ cấp I trở lên hoặc 02 công trình từ cấp II trở lên",
  "d. Cả a, b và c",
  "d",
  " Điều kiện nào dưới đây không yêu cầu đối với giám đốc QLDA hạng I?",
  "a. Đã là chủ nhiệm lập dự án ít nhất 1 dự án nhóm A hoặc 2 dự án nhóm B",
  "b. Có trình độ đại học chuyên ngành xây dựng",
  "c. Có thời gian tham gia thiết kế hoặc thi công xây dựng tối thiểu 7 năm",
  "d. Đã có chứng chỉ hành nghề thiết kế xây dựng hạng I hoặc giám sát thi côngxây dựng hạng I",
  "a",
  " Ai là người có trách nhiệm lập bản vẽ hoàn công công trình?",
  "a. Chủ đầu tư",
  "b. Nhà thầu thiết kế xây dựng",
  "c. Nhà thầu thi công xây dựng",
  "d. Nhà thầu tư vấn giám sát thi công xây dựng",
  "c",
  " Chủ thể nào có trách nhiệm lập tiến độ chi tiết thi công xây dựng côngtrình?",
  "a. Chủ đầu tư",
  "b. Nhà thầu thiết kế xây dựng công trình",
  "c. Nhà thầu thi công xây dựng công trình",
  "d. Nhà thầu tư vấn giám sát thi công xây dựng",
  "c",
  " Dự án đầu tư xây dựng có các bước thiết kế xây dựng cơ bản nào?",
  "a. Thiết kế cơ sở",
  "b. Thiết kế kỹ thuật",
  "c. Thiết kế bản vẽ thi công",
  "d. Cả a, b và c",
  "d",
  " Số bước thiết kế xây dựng do ai quyết định?",
  "a. Người quyết định đầu tư khi phê duyệt dự án",
  "b. Chủ đầu tư khi triển khai thực hiện dự án",
  "c. Tổ chức tư vấn khi lập dự án đầu tư xây dựng",
  "d. Cả 3 phương án trên đều sai",
  "a",
  " Chủ thể nào có trách nhiệm thực hiện bảo hành công trình xây dựng?",
  "a. Chủ đầu tư xây dựng công trình",
  "b. Nhà thầu thi công xây dựng công trình",
  "c. Nhà thầu thiết kế xây dựng công trình",
  "d. Cả 3 phương án trên đầu đúng",
  "b",
  " Trường hợp dự án nhóm A không có trong quy hoạch phát triển ngànhthì chủ đầu tư phải đề nghị cơ quan nào để được xem xét chấp thuận bổsung vào quy hoạch ngành trước khi lập dự án?",
  "a. Bộ quản lý ngành",
  "b. Ủy ban nhân dân cấp tỉnh nơi có dự án",
  "c. Bộ Xây dựng",
  "d. Cả 3 phương án a, b và c",
  "a",
  " Dự án đầu tư xây dựng được xem xét điều chỉnh trong những trườnghợp nào?",
  "a. Trường hợp bất khả kháng, Nhà nước thay đổi quy hoạch xây dựng",
  "b. Trường hợp điều chỉnh dự án sẽ mang lại hiệu quả cao hơn",
  "c. Khi chỉ số giá xây dựng do Bộ Xây dựng và UBND cấp tỉnh nơi có dự áncông bố lớn hơn chỉ số giá xây dựng để tính dự phòng cho yếu tố trượt giátrong tổng mức đầu tư đã được phê duyệt",
  "d. Cả a, b và c",
  "d",
  " Theo quy định của pháp luật về môi trường, những loại dự án nào phảilập báo cáo đánh giá tác động môi trường?",
  "a. Dự án quan trọng quốc gia",
  "b. Dự án đầu tư xây dựng đô thị mới, khu dân cư tập trung",
  "c. Dự án khai thác, sử dụng nước dưới đất và tài nguyên thiên nhiên có quymô lớn",
  "d. Cả a, b và c",
  "d",
  " Trường hợp công việc được xác định rõ về số lượng, khối lượng, thờigian thực hiện ngắn thì áp dụng hình thức hợp đồng nào là hợp lý nhất?",
  "a. Hợp đồng trọn gói",
  "b. Hợp đồng theo đơn giá",
  "c. Hợp đồng theo thời gian",
  "d. Hợp đồng theo đơn giá cố định",
  "a",
  " Trường hợp công việc chưa đủ điều kiện để xác định chính xác về sốlượng hoặc khối lượng thì nên áp dụng hình thức hợp đồng nào là thíchhợp nhất?",
  "a. Hợp đồng trọn gói",
  "b. Hợp đồng theo đơn giá cố định",
  "c. Hợp đồng theo thời gian",
  "d. Hợp đồng theo tỷ lệ phần trăm",
  "b",
  " Bên giao thầu có quyền chấm dứt hợp đồng trong các trường hợp nàosau đây?",
  "a. Bên nhận thầu bị phá sản hoặc Bên nhận thầu không thực hiện công việctheo hợp đồng 45 ngày liên tục",
  "b. Bên nhận thầu chuyển nhượng lợi ích của hợp đồng xây dựng cho bênkhác",
  "c. Bao gồm các đáp án a và b",
  "d. Việc chấm dứt hợp đồng là do bên giao thầu quyết định",
  "c",
  " Theo quy định của pháp luật về xây dựng, bản vẽ thiết kế xây dựng tronghồ sơ đề nghị cấp giấy phép xây dựng là bản vẽ của bước thiết kế nào?",
  "a. Thiết kế cơ sở",
  "b. Thiết kế kỹ thuật hoặc thiết kế bản vẽ thi công đã được thẩm định, phêduyệt theo quy định",
  "c. Thiết kế bản vẽ thi công đã được thẩm định, phê duyệt",
  "d. Một trong phương án a, b hoặc c",
  "b",
  " Khi khởi công xây dựng công trình yêu cầu phải có các điều kiện nàodưới đây?",
  "a. Có mặt bằng xây dựng của hạng mục, công trình khởi công",
  "b. Có thiết kế bản vẽ thi công của hạng mục, công trình xây dựng và giấyphép xây dựng",
  "c. Đáp ứng cả điều kiện nêu tại a và b",
  "d. Chỉ cần đáp ứng điều kiện a hoặc b",
  "c",
  " Ai có thẩm quyền phê duyệt điều chỉnh dự án đầu tư xây dựng?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Ban quản lý dự án",
  "d. Cơ quan quản lý nhà nước có thẩm quyền",
  "a",
  " Cơ quan chuyên môn về xây dựng là cơ quan nào?",
  "a. Cơ quan chuyên môn thuộc Bộ Xây dựng",
  "b. Cơ quan chuyên môn thuộc Bộ Giao thông vận tải, Bộ Công thương, BộNông nghiệp và phát triển nông thôn",
  "c. Các Sở Xây dựng, Sở Giao thông vận tải, Sở Công thương, Sở Nôngnghiệp và phát triển nông thôn",
  "d. Bao gồm cả a, b và c",
  "d",
  " Theo quy định của Luật Xây dựng, công tác thẩm định là việc kiểm tra,đánh giá của ai?",
  "a. Người quyết định đầu tư, chủ đầu tư, cơ quan chuyên môn về xây dựng",
  "b. Cơ quan chuyên môn của người quyết định đầu tư",
  "c. Người quyết định đầu tư, chủ đầu tư",
  "d. Tổ chức tư vấn có đủ điều kiện năng lực hoạt động xây dựng",
  "a",
  " Đối với dự án sử dụng vốn ngân sách nhà nước, chủ đầu tư là cơ quan,tổ chức nào?",
  "a. Ban quản lý dự án đầu tư xây dựng chuyên ngành, Ban quản lý dự án đầutư xây dựng khu vực",
  "b. Cơ quan, tổ chức quản lý, sử dụng công trình",
  "c. Ban quản lý dự án đầu tư xây dựng chuyên ngành, Ban quản lý dự án đầutư xây dựng khu vực và cơ quan, tổ chức quản lý sử dụng vốn để đầu tư xâydựng",
  "d. Bao gồm cả a và b",
  "c",
  " Việc điều chỉnh dự án đầu tư xây dựng sử dụng vốn nhà nước đã đượcphê duyệt do ai quyết định?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Cơ quan chuyên môn về xây dựng",
  "d. Bao gồm cả a, b và c",
  "a",
  " Trường hợp điều chỉnh dự án đầu tư xây dựng làm thay đổi địa điểm,mục tiêu đầu tư, quy mô đầu tư thì phải được ai chấp thuận?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Người quyết định đầu tư và cơ quan chuyên môn về xây dựng",
  "d. Cơ quan chuyên môn về xây dựng",
  "c",
  " Đối với dự án đầu tư xây dựng sử dụng vốn nhà nước phải đáp ứng điềukiện gì thì mới được thành lập Ban quản lý dự án đầu tư xây dựng mộtdự án?",
  "a. Là dự án nhóm A",
  "b. Là dự án nhóm A có công trình cấp đặc biệt",
  "c. Là dự án nhóm A, B, C có công trình cấp đặc biệt",
  "d. Không yêu cầu bất kể điều gì",
  "b",
  " Trong quá trình lập dự án đầu tư xây dựng, tổ chức tư vấn lập dự án cócác nghĩa vụ gì?",
  "a. Thực hiện theo nội dung hợp đồng đã được ký kết với chủ đầu tư",
  "b. Chịu trách nhiệm về chất lượng công việc theo hợp đồng đã được ký kết;",
  "c. Bồi thường thiệt hại khi sử dụng thông tin, tài liệu, tiêu chuẩn, quy chuẩn kỹthuật, giải pháp kỹ thuật, tổ chức quản lý không phù hợp và vi phạm hợp đồnglàm thiệt hại cho chủ đầu tư",
  "d. Bao gồm a, b và c",
  "d",
  " Hồ sơ của hợp đồng xây dựng gồm các tài liệu nào dưới đây?",
  "a. Văn bản thông báo trúng thầu hoặc chỉ định thầu",
  "b. Các bản vẽ thiết kế và chỉ dẫn kỹ thuật (nếu có), Biên bản đàm phán hợpđồng",
  "c. Bao gồm đáp án a và b",
  "d. Không cần các tài liệu quy định tại a và b",
  "c",
  " Sau khi công việc của hợp đồng xây dựng đã được nghiệm thu thì cóđược điều chỉnh hợp đồng không?",
  "a. Có",
  "b. Không",
  "c. Có, tùy thuộc vào sự thỏa thuận của hai bên ký kết hợp đồng",
  "d. Do người có thẩm quyền quyết định đầu tư quyết định",
  "b",
  " Cá nhân không thuộc đối tượng yêu cầu bắt buộc phải có chứng chỉhành nghề nhưng khi tham gia hoạt động xây dựng yêu cầu phải có điềukiện gì không?",
  "a. Không yêu cầu phải có điều kiện gì",
  "b. Phải có văn bằng hoặc chứng chỉ đào tạo phù hợp với công việc thực hiện",
  "c. Có văn bằng hoặc chứng chỉ đào tạo phù hợp với công việc thực hiện và cókinh nghiệm tối thiểu 3 năm tham gia hoạt động xây dựng",
  "d. Yêu cầu có 5 năm kinh nghiệm đối với công việc thực hiện",
  "b",
  " Đối với dự án đầu tư xây dựng sử dụng vốn đầu tư công thì Báo cáonghiên cứu tiền khả thi đầu tư xây dựng được lập theo quy định nào?",
  "a. Pháp luật về xây dựng",
  "b. Pháp luật về đầu tư công",
  "c. Pháp luật về xây dựng và pháp luật về đầu tư công",
  "d. Pháp luật về đầu tư công, pháp luật về đầu tư, pháp luật xây dựng",
  "d",
  " Đối với dự án đầu tư xây dựng thực hiện theo hình thức PPP thì việcthẩm định dự án được thực hiện theo yêu cầu đối với dự án sử dụngnguồn vốn nào?",
  "a. Vốn ngân sách nhà nước",
  "b. Vốn nhà nước ngoài ngân sách",
  "c. Vốn khác",
  "d. Vốn khác hoặc vốn nhà nước tùy thuộc vào quy mô dự án",
  "b",
  " Đối với dự án đầu tư xây dựng sử dụng vốn ngân sách của xã có tổngmức đầu tư đến 10 tỷ đồng thì cơ quan, tổ chức nào làm chủ đầu tư dựán này?",
  "a. Ủy ban nhân dân xã",
  "b. Ủy ban nhân dân huyện",
  "c. Ban quản lý dự án đầu tư xây dựng do UBND xã thành lập",
  "d. Ban quản lý dự án đầu tư xây dựng do UBND huyện thành lập",
  "a",
  " Đối với dự án đầu tư xây dựng sử dụng vốn nhà nước ngoài ngân sáchdo Tập đoàn kinh tế, Tổng công ty nhà nước quyết định đầu tư thì cơquan, tổ chức nào được giao làm chủ đầu tư?",
  "a. Ban quản lý dự án đầu tư xây dựng chuyên ngành",
  "b. Ban quản lý dự án đầu tư xây dựng khu vực",
  "c. Cơ quan, tổ chức quản lý sử dụng vốn thuộc Tập đoàn, Tổng công ty",
  "d. Do Tập đoàn, Tổng công ty quyết định một trong các hình thức trên",
  "d",
  " Cơ quan nào có trách nhiệm lấy ý kiến của các cơ quan quản lý nhànước về những lĩnh vực có liên quan đến dự án đầu tư xây dựng trongquá trình thẩm định?",
  "a. Cơ quan chủ trì thẩm định dự án, thẩm định thiết kế cơ sở",
  "b. Cơ quan chuyên môn của người quyết định đầu tư",
  "c. Cơ quan chuyên môn về xây dựng",
  "d. Chủ đầu tư",
  "a",
  " Cá nhân đề nghị cấp chứng chỉ hành nghề hoạt động xây dựng yêu cầuphải đáp ứng các điều kiện chung gì?",
  "a. Có đủ năng lực hành vi dân sự theo quy định của pháp luật",
  "b. Có trình độ chuyên môn được đào tạo, thời gian và kinh nghiệm tham giacông việc phù hợp với nội dung đề nghị cấp chứng chỉ hành nghề và phải đạtkết quả sát hạch theo quy định",
  "c. Bao gồm a và b",
  "d. Chỉ cần đạt được kết quả sát hạch theo quy định là đủ",
  "c",
  " Tổ chức đề nghị cấp chứng chỉ năng lực hoạt động xây dựng yêu cầuphải đáp ứng các điều kiện gì?",
  "a. Những cá nhân chủ chốt của tổ chức phải có chứng chỉ hành nghề phù hợpvới lĩnh vực và hạng năng lực mà tổ chức đề nghị cấp chứng chỉ năng lực",
  "b. Tổ chức đã thực hiện công việc tương tự loại, cấp công trình",
  "c. Phải có thời gian tham gia hoạt động xây dựng tối thiểu 3 năm",
  "d. Đáp ứng cả điều kiện a và b ở trên",
  "d",
  " Nhà thầu phụ phải chịu trách nhiệm với ai về công việc do mình thựchiện?",
  "a. Chủ đầu tư",
  "b. Thầu chính hoặc tổng thầu",
  "c. Chủ đầu tư và thầu chính hoặc tổng thầu",
  "d. Chịu trách nhiệm với ai là căn cứ vào các điều khoản cam kết trong hợpđồng xây dựng",
  "b",
  " Trường hợp phải thuê thầu phụ để thực hiện một số phần việc trong hợpđồng đã ký kết với chủ đầu tư thì cần phải có chấp thuận của ai?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. người quyết định đầu tư hoặc chủ đầu tư tùy thuộc vào từng gói thầu",
  "d. Không cần phải có sự chấp thuận của cơ quan, tổ chức nào",
  "b",
  " Bảo đảm thực hiện hợp đồng xây dựng phải được nộp cho bên giaothầu khi nào?",
  "a. Trước thời điểm hợp đồng có hiệu lực",
  "b. Sau khi hợp đồng được ký kết",
  "c. Trước khi khởi công xây dựng công trình",
  "d. Bao gồm cả a, b và c",
  "a",
  " Bảo đảm thực hiện hợp đồng của nhà thầu thi công xây dựng có hiệulực đến khi nào?",
  "a. Đến khi nhà thầu đã hoàn thành các nghĩa vụ theo hợp đồng",
  "b. Sau khi chủ đầu tư đã nhận được bảo đảm bảo hành của nhà thầu",
  "c. Đáp án a hoặc b do hai bên thỏa thuận trong hợp đồng",
  "d. Sau khi công việc theo hợp đồng đã hoàn thành bàn giao chủ chủ đầu tư",
  "c",
  " Cá nhân chưa được cấp chứng chỉ hành nghề hoạt động xây dựng cóđược tham gia hoạt động xây dựng không?",
  "a. Có",
  "b. Không",
  "c. Có, nhưng chỉ được tham gia các công việc của công trình cấp IV",
  "d. Có, nhưng phải có văn bằng, chứng chỉ đào tạo phù hợp với công việc màcá nhân đó thực hiện",
  "d",
  " Cá nhân có độ tuổi trên 70 nếu đáp ứng đủ điều kiện năng lực theo quyđịnh có được xem xét cấp chứng chỉ hành nghề hoạt động xây dựngkhông?",
  "a. Có",
  "b. Không",
  "c. Có, nhưng phải có giấy khám sức khỏe đủ điều kiện của bác sỹ",
  "d. Có, nhưng chỉ được cấp chứng chỉ hành nghề thiết kế công trình xây dựng",
  "a",
  " Tổ chức hoạt động xây dựng mới được thành lập có những cá nhân cóchứng chỉ hành nghề hạng 1 phù hợp với lĩnh vực mà tổ chức đề nghịcấp chứng chỉ năng lực hoạt động xây dựng, nhưng chưa ký hợp đồngđể thực hiện bất kể công việc gì trong hoạt động đầu tư xây dựng thì cóđược cấp chứng chỉ năng lực hoạt động xây dựng hạng 1 không?",
  "a. Có",
  "b. Không",
  "c. Có, nhưng chỉ được xem cấp chứng chỉ hành năng lực cho lĩnh vực địnhgiá xây dựng",
  "d. Có, nhưng chỉ được xem cấp chứng chỉ hành năng lực cho các lĩnh vựcgiám sát thi công xây dựng, kiểm định xây dựng",
  "b",
  " Bước thiết kế công trình xây dựng nào mới đủ điều kiện để khởi côngxây dựng công trình?",
  "a. Thiết kế cơ sở",
  "b. Thiết kế kỹ thuật",
  "c. Thiết kế bản vẽ thi công",
  "d. Một trong ba bước thiết kế trên đều được",
  "c"];