List<String> list_field_gstcxd =[" Những người nào sau đây tham gia và ký biên bản nghiệm thucông việc xây dựng",
  "a. Người giám sát thi công xây dựng công trình và người phụ trách kỹthuật thi công trực tiếp của nhà thầu thi công xây dựng công trình",
  "b. Người của Chủ đầu tư/Ban quản lý dự án, người giám sát thi côngxây dựng công trình và người phụ trách kỹ thuật thi công trực tiếp củanhà thầu thi công xây dựng công trình",
  "c. Người của Chủ đầu tư/Ban quản lý dự án và người phụ trách kỹthuật thi công trực tiếp của nhà thầu thi công xây dựng công trình",
  "d. Cả ba đáp án trên",
  "a",
  " Ai là người có trách nhiệm tổ chức lập hồ sơ hoàn thành côngtrình xây dựng?",
  "a. Nhà thầu thi công xây dựng",
  "b. Chủ đầu tư",
  "c. Nhà thầu giám sát thi công xây dựng",
  "d. Cơ quan quản lý nhà nước có thẩm quyền",
  "b",
  " Thời hạn bảo trì công trình được tính như thế nào?",
  "a. Sau khi kết thúc thời hạn bảo hành cho đến khi hết niên hạn sửdụng công trình.",
  "b. Từ ngày nghiệm thu đưa công trình xây dựng vào sử dụng cho đếnkhi hết niên hạn sử dụng công trình.",
  "c. Từ ngày chủ đầu tư bàn giao công trình cho chủ sở hữu hoặcngười quản lý sử dụng công trình.",
  "d. Từ ngày có văn bản chấp thuận kết quả nghiệm thu của chủ đầu tư",
  "b",
  " Dự án nào sau đây yêu cầu phải lập Báo cáo nghiên cứu tiền khảthi đầu tư xây dựng ?",
  "a. Dự án quan trọng quốc gia",
  "b. Dự án quan trọng quốc gia, dự án nhóm A và nhóm B",
  "c. Dự án quan trọng quốc gia và dự án nhóm A",
  "d. Cả ba đáp án trên",
  "c",
  " Việc áp dụng quy chuẩn kỹ thuật trong hoạt động đầu tư xâydựng là:",
  "a. Bắt buộc",
  "b. Khuyến khích",
  "c. Tự nguyện",
  "d. Thoả thuận",
  "a",
  " Quy định áp dụng Tiêu chuẩn kỹ thuật trong hoạt động đầu tưxây dựng như thế nào?",
  "a. Bắt buộc đối với các tiêu chuẩn được viện dẫn trong quy chuẩn kỹthuật hoặc văn bản quy phạm pháp luật khác có liên quan",
  "b. Khuyến khích áp dụng",
  "c. Theo nguyên tắc tự nguyện",
  "d. Đáp án a và c",
  "d",
  " Những loại tiêu chuẩn nào sau đây bắt buộc áp dụng?",
  "a. TCVN",
  "b. Tiêu chuẩn nước ngoài",
  "c. Các tiêu chuẩn nằm trong danh mục tiêu chuẩn đã được ngườiquyết định đầu tư phê duyệt",
  "d. Danh mục tiêu chuẩn do tư vấn thiết kế đệ trình",
  "c",
  " Nhiệm vụ khảo sát xây dựng do chủ thể nào lập?",
  "a. Nhà thầu thiết kế",
  "b. Tổ chức, cá nhân có đủ điều kiện năng lực",
  "c. Nhà thầu thiết kế hoặc tổ chức, cá nhân có đủ điều kiện năng lực",
  "d. Người quyết định đầu tư",
  "c",
  " Phương án kỹ thuật khảo sát xây dựng do chủ thể nào lập?",
  "a. Nhà thầu thiết kế",
  "b. Nhà thầu Khảo sát",
  "c. Tư vấn giám sát",
  "d. Chủ đầu tư",
  "b",
  " Chỉ dẫn kỹ thuật phải phù hợp với nội dung nào sau đây?",
  "a. Quy chuẩn kỹ thuật,",
  "b. Tiêu chuẩn áp dụng cho công trình xây dựng được phê duyệt",
  "c. Theo yêu cầu của thiết kế xây dựng công trình.",
  "d. Cả phương án a,b,c",
  "d",
  " Bắt buộc thực hiện lập chỉ dẫn kỹ thuật riêng đối với công trìnhnào sau đây?",
  "a. Công trình ảnh hưởng đến an toàn cộng đồng",
  "b. Toàn bộ các cấp",
  "c. Cấp đặc biệt, cấp I và cấp II",
  "d. Công trình quan trọng quốc gia",
  "c",
  " Đối với công trình xây dựng sử dụng vốn ngân sách nhà nước ailà người phê duyệt thiết kế kỹ thuật, dự toán xây dựng trườnghợp thiết kế ba bước?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Giám đốc Ban quản lý dự án",
  "d. Không phải các đáp án trên",
  "a",
  " Đối với công trình xây dựng sử dụng vốn ngân sách nhà nước ailà người phê duyệt thiết kế bản vẽ thi công trong trường hợpthiết kế ba bước?",
  "a. Chủ đầu tư",
  "b. Người quyết định đầu tư",
  "c. Tư vấn thiết kế",
  "d. Tư vấn giám sát",
  "a",
  " Cơ quan chuyên môn về xây dựng theo phân cấp yêu cầu chủđầu tư lựa chọn tổ chức tư vấn thực hiện thẩm tra dự toán xâydựng công trình làm cơ sở cho việc thẩm định trước khi trìnhcấp có thẩm quyền phê duyệt đối với công trình dự án nhóm nào?",
  "a. Các công trình thuộc dự án quan trọng quốc gia, dự án nhóm A",
  "b. Các công trình thuộc dự án quan trọng quốc gia, dự án nhómA,B,C",
  "c. Các công trình thuộc dự án quan trọng quốc gia, dự án nhóm A, Bvà C có kỹ thuật phức tạp hoặc áp dụng công nghệ cao",
  "d. Các công trình có ảnh hưởng đến an toàn cộng đồng",
  "c",
  " Ai là người có thẩm quyền phê duyệt thiết kế biện pháp thicông?",
  "a. Chủ đầu tư",
  "b. Nhà thầu thi công xây dựng",
  "c. Người quyết định đầu tư",
  "d. Tư vấn giám sát",
  "a",
  " Nhà thầu thi công phải trình chủ đầu tư chấp thuận những tàiliệu nào sau đây?",
  "a. Kế hoạch tổ chức thí nghiệm và kiểm định chất lượng, quan trắc,đo đạc các thông số kỹ thuật của công trình theo yêu cầu thiết kế vàchỉ dẫn kỹ thuật;",
  "b. Biện pháp kiểm tra, kiểm soát chất lượng vật liệu, sản phẩm, cấukiện, thiết bị được sử dụng cho công trình; thiết kế biện pháp thi công,trong đó quy định cụ thể các biện pháp, bảo đảm an toàn cho người,máy, thiết bị và công trình;",
  "c. Kế hoạch kiểm tra, nghiệm thu công việc xây dựng, nghiệm thu giaiđoạn thi công xây dựng hoặc bộ phận (hạng mục) công trình xâydựng, nghiệm thu hoàn thành hạng mục công trình, công trình xâydựng;",
  "d. Toàn bộ các tài liệu nêu trên",
  "d",
  " Việc giám sát thi công xây dựng công trình phải đảm bảo cácyêu cầu sau ?",
  "a. Thực hiện trong suốt quá trình thi công từ khi khởi công xây dựng,trong thời gian thực hiện cho đến khi hoàn thành và nghiệm thu côngviệc, công trình xây dựng;",
  "b. Giám sát thi công công trình đúng với thiết kế xây dựng được phêduyệt, tiêu chuẩn áp dụng, quy chuẩn kỹ thuật, quy định về quản lý,sử dụng vật liệu xây dựng, chỉ dẫn kỹ thuật và hợp đồng xây dựng;",
  "c. Trung thực khách quan, không vụ lợi;",
  "d. Tất cả các yêu cầu trên",
  "d",
  " Nhà thầu giám sát thi công xây dựng có trách nhiệm gì sau đây?",
  "a. Thực hiện giám sát theo đúng hợp đồng",
  "b. Từ chối nghiệm thu khi công trình không đạt yêu cầu về chất lượng",
  "c. Giám sát việc thực hiện các quy định về an toàn, bảo vệ môitrường",
  "d. Tất cả các điều trên",
  "d",
  " Tổ chức giám sát thi công xây dựng phải độc lập với các nhàthầu thi công xây dựng công trình trong các trường hợp nào sauđây ?",
  "a. Các công trình đầu tư bằng nguồn vốn ngân sách nhà nước vànguồn vốn nhà nước ngoài ngân sách",
  "b. Các công trình đầu tư bằng nguồn vốn khác",
  "c. Các công trình áp dụng đầu tư theo hình thức đồi tác công tư",
  "d. Tất cả các trường hợp trên",
  "a",
  " Bản vẽ hoàn công là bản vẽ nào sau đây?",
  "a. Là bản vẽ công trình xây dựng hoàn thành, trong đó thể hiện vị trí,kích thước, vật liệu và thiết bị được sử dụng thực tế",
  "b. Là bản vẽ của thiết kế kỹ thuật",
  "c. Là bản vẽ của thiết kế bản vẽ thi công",
  "d. Tất cả các đáp án trên",
  "a",
  " Thẩm quyền kiểm tra biện pháp thi công xây dựng của nhà thầuthi công?",
  "a. Tư vấn thiết kế",
  "b. Người giám sát thi công xây dựng của chủ đầu tư",
  "c. Đơn vị kiểm định độc lập",
  "d. Cả ba đáp án trên",
  "b",
  " Nhật ký thi công xây dựng công trình do ai lập?",
  "a. Do Chủ đầu tư lập;",
  "b. Do nhà thầu thi công xây dựng lập cho từng gói thầu hoặc toàn bộcông trình xây dựng;",
  "c. Do tổ chức tư vấn giám sát lập.",
  "d. Cả ba đáp án trên",
  "b"];