List<String> list_field_tkxd=["Trong hoạt động xây dựng có các loại hình khảo sát xây dựngnào?",
  "a. Khảo sát địa hình",
  "b. Khảo sát địa chất công trình",
  "c. Khảo sát địa chất thủy văn",
  "d. Bao gồm cả 3 loại hình nêu tại a, b và c",
  "d",
  " Nhiệm vụ khảo sát xây dựng phải phù hợp với các nội dung nàosau đây?",
  "a. Loại và nhóm dự án đầu tư xây dựng",
  "b. Nhiệm vụ thiết kế xây dựng công trình",
  "c. Chủ trương đầu tư xây dựng",
  "d. Loại, cấp công trình xây dựng, loại hình khảo sát và bước thiết kế",
  "d",
  " Chủ đầu tư không có nghĩa vụ nào dưới đây?",
  "a. Lựa chọn nhà thầu khảo sát xây dựng, giám sát khảo sát xây dựngtrong trường hợp không tự thực hiện khảo sát xây dựng, giám sátkhảo sát xây dựng",
  "b. Cung cấp cho nhà thầu khảo sát xây dựng thông tin, tài liệu có liênquan đến công tác khảo sát",
  "c. Điều chỉnh nhiệm vụ khảo sát xây dựng theo yêu cầu của nhà thầuthiết kế",
  "d. Bồi thường thiệt hại khi cung cấp thông tin, tài liệu không phù hợp,vi phạm hợp đồng khảo sát xây dựng",
  "c",
  " Thiết kế xây dựng công trình phải đáp ứng yêu cầu nào dướiđây?",
  "a. Đáp ứng yêu cầu của nhiệm vụ thiết kế; phù hợp với nội dung dựán đầu tư xây dựng được duyệt, quy hoạch xây dựng, cảnh quan kiếntrúc, điều kiện tự nhiên, văn hóa - xã hội tại khu vực xây dựng",
  "b. Tuân thủ tiêu chuẩn áp dụng, quy chuẩn kỹ thuật, quy định củapháp luật về sử dụng vật liệu xây dựng, đáp ứng yêu cầu về côngnăng sử dụng, công nghệ áp dụng (nếu có); bảo đảm an toàn chịulực, an toàn trong sử dụng, mỹ quan, bảo vệ môi trường",
  "c. Có giải pháp thiết kế phù hợp và chi phí xây dựng hợp lý; bảo đảmđồng bộ trong từng công trình và với các công trình liên quan",
  "d. Cả 3 yêu cầu nêu tại a, b và c",
  "d",
  " Thiết kế, dự toán xây dựng công trình triển khai sau thiết kế cơsở gồm những nội dung chủ yếu gì?",
  "a. Phương án kiến trúc, phương án công nghệ (nếu có)",
  "b. Phương án kết cấu, loại vật liệu chủ yếu",
  "c. Dự toán xây dựng",
  "d. Bao gồm cả 3 nội dung nêu tại a, b và c",
  "d",
  " Cơ quan nào chủ trì tổ chức thẩm định thiết kế kỹ thuật, dự toánxây dựng công trình thuộc dự án sử dụng vốn ngân sách nhànước?",
  "a. Cơ quan chuyên môn về xây dựng",
  "b. Cơ quan chuyên môn của người quyết định đầu tư",
  "c. Cơ quan quản lý kỹ thuật của chủ đầu tư",
  "d. Cả a, b và c đều không đúng",
  "a",
  " Đối với dự án sử dụng vốn ngân sách nhà nước, ai là người phêduyệt thiếtkế bản vẽ thi công và dự toán xây dựng trong trường hợp thiếtkế 2 bước?",
  "a. Người có thẩm quyền quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khuvực",
  "d. Cơ quan chuyên môn của người quyết định đầu tư",
  "a",
  " Đối với dự án sử dụng vốn nhà nước ngoài ngân sách, ai làngười phê duyệt thiết kế bản vẽ thi công và dự toán xây dựng,trong trường hợp thiết kế 2 bước?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khuvực",
  "d. Cơ quan chuyên môn của người quyết định đầu tư",
  "b",
  " Trường hợp dự án chỉ yêu cầu lập Báo cáo kinh tế kỹ thuật đầutư xây dựng thì ai là người phê duyệt thiết kế bản vẽ thi công, dựtoán xây dựng công trình?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Ban QLDA đầu tư xây dựng chuyên ngành hoặc Ban QLDA khuvực",
  "d. Cơ quan chuyên môn của người quyết định đầu tư",
  "a",
  " Tổ chức nào không được thực hiện thẩm tra thiết kế, dự toáncông trình X?",
  "a. Tổ chức đã thiết kế xây dựng công trình X",
  "b. Cơ quan chuyên môn về xây dựng",
  "c. Ban quản lý dự án đầu tư xây dựng thuộc chủ đầu tư",
  "d. Tổ chức tư vấn giám sát thi công xây dựng công trình X",
  "a",
  " Thiết kế xây dựng công trình không được thay đổi khi nào?",
  "a. Khi điều chỉnh dự án đầu tư xây dựng có yêu cầu thay đổi thiết kếcơ sở",
  "b. Trong quá trình thi công xây dựng, phát hiện yếu tố bất hợp lý nếukhông thay đổi sẽ ảnh hưởng tới chất lượng công trình xây dựng",
  "c. Khi điều chỉnh tổng mức đầu tư của dự án do chỉ số giá xây dựngtăng so với chỉ số giá xây dựng lập dự phòng cho yếu tố trượt giá",
  "d. Khi thiết kế bước trước đã được phê duyệt có thay đổi",
  "c",
  " Đối với trường hợp thiết kế 1 bước thì thiết kế bản vẽ thi côngđược lập trên cơ sở nào?",
  "a. Nhiệm vụ thiết kế được người có thẩm quyền quyết định đầu tưphê duyệt",
  "b. Nhiệm vụ thiết kế được chủ đầu tư phê duyệt",
  "c. Phương án thiết kế do nhà thầu tư vấn thiết kế đề xuất",
  "d. Cả 3 đáp án a, b và c đều không đúng",
  "b",
  " Theo phân cấp công trình, kho chứa vật liệu nổ thuộc cấp đặcbiệt, theo quy định tại Nghị định 59/2015/NĐ-CP thì cơ quanchuyên môn về xây dựng trực thuộc Bộ Công thương thẩm địnhthiết kế, dự toán xây dựng công trình này, vậy những công trìnhcòn lại của dự án thì cơ quan nào thẩm định?",
  "a. Cơ quan chuyên môn về xây dựng thuộc Bộ Công thương",
  "b. Cơ quan chuyên môn về xây dựng thuộc Bộ Xây dựng",
  "c. Cơ quan chuyên môn của người quyết định đầu tư",
  "d. Sở quản lý công trình xây dựng chuyên ngành nơi xây dựng cáccông trình",
  "a",
  " Thiết kế kỹ thuật, dự toán xây dựng công trình thuộc dự án sửdụng vốn ngân sách nhà nước đã được cơ quan chuyên môn vềxây dựng thẩm định. Trong trường hợp, khi thi công xây dựngphát sinh điều chỉnh khối lượng nhưng không ảnh hưởng tới antoàn công trình thì phải trình cơ quan nào thẩm định lại trước khiphê duyệt điều chỉnh?",
  "a. Chủ đầu tư",
  "b. Người quyết định đầu tư",
  "c. Cơ quan chuyên môn về xây dựng",
  "d. Ban quản lý dự án",
  "a",
  " Cá nhân có trình độ cao đẳng, trung cấp có chứng chỉ hành nghềthiết kế được chủ trì thiết kế công trình cấp mấy?",
  "a. Cấp II trở xuống",
  "b. Cấp III trở xuống",
  "c. Cấp IV",
  "d. Không được chủ trì thiết kế xây dựng",
  "b"];