List<String> list_field_dgxd =[" Tổng mức đầu tư xây dựng đã phê duyệt của dự án sử dụngvốn nhà nước được điều chỉnh trong trường hợp nào:",
  "a. Giá vật liệu thay đổi",
  "b. Giá nhân công thay đổi",
  "c. Chỉ số giá xây dựng do Bộ Xây dựng, UBND cấp tỉnh công bốtrong thời gian thực hiện dự án lớn hơn chỉ số giá xây dựng được sửdụng để tính dự phòng trượt giá trong tổng mức đầu tư được duyệt",
  "d. Cả a, b, c đều đúng.",
  "c",
  " Trong phạm vi tổng mức đầu tư đã được duyệt, Chủ đầu tưđược quyền:",
  "a. Bổ sung công trình, hạng mục công trình chưa có trong thiết kế cơsở.",
  "b. Điều chỉnh cơ cấu các khoản mục chi phí",
  "c. Thay đổi cơ cấu nguồn vốn",
  "d. Điều chỉnh quy mô, công suất của dự án;",
  "b",
  " Theo quy định hiện hành về quản lý chi phí đầu tư xây dựng,chi phí dự phòng cho yếu tố trượt giá trong dự toán xây dựngcông trình không phụ thuộc những yếu tố nào sau đây?",
  "a. Thời gian xây dựng công trình;",
  "b. Giá trị dự toán xây dựng công trình trước thuế",
  "c. Lãi vay trong thời gian xây dựng;",
  "d. Chỉ số giá xây dựng",
  "c",
  " Trực tiếp phí khác trong dự toán chi phí xây dựng được xácđịnh từ các chi phí nào?",
  "a. Chi phí vật liệu, chi phí nhân công, chi phí máy thi công;",
  "b. Chi phí xây dựng và chi phí lắp đặt, thí nghiệm hiệu chỉnh thiết bịtrước thuế giá trị gia tăng",
  "c. Chi phí trực tiếp và chi phí chung",
  "d. Cả a, b, c đều sai",
  "d",
  " Định mức kinh tế - kỹ thuật trong xây dựng gồm những loạiđịnh mức nào ?",
  "a. Định mức dự toán xây dựng công trình",
  "b. Định mức sử dụng vật liệu, định mức lao động, định mức năngsuất máy và thiết bị thi công;",
  "c. Định mức cơ sở",
  "d. a và c",
  "d",
  " Định mức tỷ lệ chi phí một số công việc thuộc hạng mục chungkhông xác định được khối lượng từ thiết kế đã bao gồm chi phíxây dựng phòng thí nghiệm tại hiện trường chưa?",
  "a. Đã bao gồm",
  "b. Chưa bao gồm",
  "c. Tùy theo giá trị chi phí xây dựng và chi phí lắp đặt, thí nghiệm hiệuchỉnh thiết bị trước thuế.",
  "d. Cả a, b, c đều sai",
  "c",
  " Định mức dự toán xây dựng công trình của các công việc đặcthù chuyên ngành do cơ quan nào dưới đây ban hành?",
  "a. Bộ Xây dựng;",
  "b. Bộ, cơ quan ngang Bộ;",
  "c. Người quyết định đầu tư;",
  "d. Bộ quản lý công trình xây dựng chuyên ngành, Ủy ban nhân dâncấp tỉnh.",
  "d",
  " Dự toán gói thầu của công trình cấp I thuộc Dự án sử dụng vốnngân sách nhà nước do cơ quan nào dưới đây thẩm định?",
  "a. Bộ Xây dựng, Bộ quản lý công trình xây dựng chuyên ngành thẩmđịnh.",
  "b. Sở Xây dựng, Sở quản lý công trình xây dựng chuyên ngành thẩmđịnh",
  "c. Chủ đầu tư.",
  "d. Người quyết định đầu tư.",
  "c",
  " Dự toán xây dựng công trình không bao gồm chi phí nào sauđây?",
  "a. Chi phí bồi thường, hỗ trợ và tái định cư",
  "b. Chi phí rà phá bom mìn, vật nổ",
  "c. Chi phí hạng mục chung",
  "d. Chi phí lưu kho, lưu bãi, lưu Container tại cảng Việt Nam đối vớithiết bị nhập khẩu",
  "a",
  " Đối với dự án sử dụng vốn nhà nước (không phải là dự án quantrọng quốc gia, không phải dự án do Thủ tướng quyết định đầutư), cơ quan nào sau đây phê duyệt quyết toán vốn đầu tư?",
  "a. Người quyết định đầu tư",
  "b. Bộ Tài chính",
  "c. Sở Tài chính",
  "d. Chủ đầu tư",
  "a",
  " Đơn giá nhân công trong dự toán xây dựng công trình do đơnvị nào sau đây quyết định?",
  "a. Ủy ban nhân nhân cấp tỉnh.",
  "b. Đơn vị tư vấn lập dự toán.",
  "c. Người quyết định đầu tư.",
  "d. Chủ đầu tư.",
  "d",
  " Theo quy định về quản lý chi phí đầu tư xây dựng hiện hành,đơn giá nhân công xây dựng trên địa bàn địa phương do cơquan nào sau đây ban hành?",
  "a. Ủy ban nhân dân cấp tỉnh.",
  "b. Sở Xây dựng.",
  "c. Liên sở Tài chính - Xây dựng.",
  "d. Chủ đầu tư.",
  "a",
  " Suất vốn đầu tư xây dựng công trình được sử dụng để xác địnhchỉ tiêu nào dưới đây?",
  "a. Tổng mức đầu tư xây dựng công trình.",
  "b. Giá xây dựng tổng hợp công trình.",
  "c. Dự toán xây dựng công trình.",
  "d. Chi phí xây dựng trong tổng mức đầu tư xây dựng công trình",
  "a",
  " Chi phí quản lý dự án không bao gồm những yếu tố nào sauđây?",
  "a. Bảo hiểm y tế, bảo hiểm thất nghiệp.",
  "b. Chi phí tổ chức thẩm định dự án đầu tư.",
  "c. Chi phí nghiệm thu bàn giao công trình.",
  "d. Chi phí hội nghị, hội thảo, tập huấn, đào tạo.",
  "c",
  " Chi phí thiết kế công trình không bao gồm các chi phí để thựchiện các công việc nào sau đây?",
  "a. Khảo sát xây dựng phục vụ thiết kế.",
  "b. Làm mô hình công trình.",
  "c. Đánh giá tác động môi trường; lập báo cáo đánh giá khoáng sảntrong khu vực ảnh hưởng của công trình.",
  "d. Cả 3 phương án trên.",
  "d",
  " Dự toán chi phí khảo sát bao gồm những chi phí nào sau đây ?",
  "a. Chi phí lập phương án kỹ thuật khảo sát.",
  "b. Chi phí lập báo cáo kết quả khảo sát.",
  "c. Chi phí chỗ ở tạm.",
  "d. Cả 3 phương án trên.",
  "d",
  " Chi phí giám sát thi công xây dựng theo quy định được tínhnhư thế nào ?",
  "a. Bằng tỷ lệ % theo quy định nhân với chi phí xây dựng (chưa cóthuế giá trị gia tăng) trong dự toán gói thầu xây dựng được duyệt.",
  "b. Bằng tỷ lệ % theo quy định nhân với chi phí xây dựng (chưa cóthuế giá trị gia tăng) trong dự toán công trình xây dựng được duyệt.",
  "c. Bằng tỷ lệ % theo quy định nhân với chi phí thiết bị (chưa có thuếgiá trị gia tăng) trong dự toán gói thầu xây dựng được duyệt.",
  "d. Bằng tỷ lệ % theo quy định nhân với chi phí thiết bị (chưa có thuếgiá trị gia tăng) trong dự toán công trình xây dựng được duyệt.",
  "a",
  " Suất vốn đầu tư xây dựng công trình bao gồm những chi phínào sau đây:",
  "a. Chi phí xây dựng, thiết bị (đã bao gồm thuế GTGT).",
  "b. Chi phí xây dựng, thiết bị, quản lý dự án, tư vấn đầu tư xây dựngvà các khoản chi phí khác (chưa bao gồm thuế GTGT cho các chiphí nêu trên).",
  "c. Chi phí xây dựng, thiết bị, quản lý dự án, tư vấn đầu tư xây dựngvà các khoản chi phí khác (đã bao gồm thuế GTGT cho các chi phínêu trên).",
  "d. Chi phí xây dựng, thiết bị, quản lý dự án, tư vấn đầu tư xây dựng,các khoản chi phí khác và chi phí dự phòng (đã bao gồm thuế GTGTcho các chi phí nêu trên).",
  "c",
  " Khi quy đổi chi phí để tính toán suất vốn đầu tư xây dựng côngtrình cần căn cứ vào hệ số nào sau đây:",
  "a. Hệ số khu vực/ vùng.",
  "b. Hệ số điều chỉnh giá xây dựng công trình.",
  "c. Hệ số khu vực/ vùng và hệ số điều chỉnh giá xây dựng công trình.",
  "d. Hệ số khu vực/ vùng, hệ số điều chỉnh giá xây dựng công trình vàchỉ số giá xây dựng công trình.",
  "c",
  " Nguyên tắc khi lựa chọn loại vật liệu, nhân công, máy thi côngchủ yếu để tính toán chỉ số giá xây dựng là chi phí cho loại vậtliệu, nhân công, máy thi công chủ yếu đó chiếm tỷ trọng baonhiêu trong chi phí vật liệu, nhân công, máy thi công tương ứngcủa công trình:",
  "a. Từ 50% - 60%.",
  "b. Từ 60% - 70%.",
  "c. Từ 70% - 80%.",
  "d. Trên 80%.",
  "d",
  " Các máy thi công xây dựng chủ yếu để xác định chỉ số giá máythi công xây dựng công trình không bao gồm loại máy nào sauđây:",
  "a. Máy bơm bê tông tự hành, máy đầm, máy khoan bê tông cầm tay.",
  "b. Sà lan, ca nô, phao thép, xáng cạp, tàu hút bụng tự hành.",
  "c. Máy đào, máy ủi, máy xúc, máy san tự hành.",
  "d. Cần trục ô tô, cần trục bánh hơi, cần trục bánh xích, cần trục tháp,vận thăng.",
  "b",
  " Câu nào là đáp án sai trong các câu sau:",
  "a. Khối lượng cốt thép phải được đo bóc, phân loại theo chủng loạithép (thép thường và thép dự ứng lực, thép trơn, thép vằn)",
  "b. Khối lượng cốt thép phải được đo bóc, phân loại theo mác thép,nhóm thép, đường kính cốt thép, chi tiết bộ phận kết cấu (móng, cột,tường…)",
  "c. Khối lượng cốt thép phải được đo bóc, phân loại theo điều kiện thicông",
  "d. Khối lượng cốt thép được đo bóc không bao gồm khối lượng dâybuộc, mối nối chồng, nối ren, nối ống, miếng đệm, con kê, bu lôngliên kết…",
  "d",
  " Một dự án đầu tư xây dựng Trường đại học sử dụng vốn ngânsách nhà nước được phê duyệt trước ngày 01/01/2015, sau 2năm thực hiện phải điều chỉnh lại tổng mức đầu tư, vậy thẩmquyền thẩm định dự án điều chỉnh thuộc trách nhiệm của ai?",
  "a. Người quyết định đầu tư",
  "b. Chủ đầu tư",
  "c. Cơ quan chuyên môn về xây dựng",
  "d. Cơ quan đã chủ trì thẩm định đối với dự án, thiết kế cơ sở đượcduyệt",
  "d",
  " Dự án đầu tư xây dựng được phê duyệt ngày 25/3/2015, khi thiếtkế kỹ thuật, thực hiện lập dự toán xây dựng công trình của dựán này theo quy định nào?",
  "a. Nghị định số 112/2009/NĐ-CP ngày 14/12/2009",
  "b. Nghị định số 32/2015/NĐ-CP ngày 25/3/2015",
  "c. Do người quyết định đầu tư quyết định",
  "d. Do cơ quan chủ trì thẩm định quyết định",
  "a",
  " Trên cơ sở kế hoạch vốn được giao, cơ quan thanh toán vốnđầu tư có trách nhiệm thanh toán vốn đầu tư theo đề nghị thanhtoán của chủ đầu tư hoặc đại diện hợp pháp của chủ đầu tưtrong thời hạn bao nhiêu ngày?",
  "a. 7 ngày",
  "b. 9 ngày",
  "c. 13 ngày",
  "d. 16 ngày",
  "a",
  " Chủ đầu tư có trách nhiệm lập hồ sơ quyết toán vốn đầu tư xâydựng công trình và quy đổi vốn đầu tư công trình xây dựng saukhi hoàn thành được nghiệm thu bàn giao đưa vào sử dụng đểtrình người quyết định đầu tư phê duyệt chậm nhất là bao nhiêutháng (đối với dự án nhóm B)?",
  "a. 6 tháng",
  "b. 7 tháng",
  "c. 9 tháng",
  "d. 12 tháng",
  "a",
  " UBND cấp tỉnh có thẩm quyền nào dưới đây?",
  "a. Ban hành hệ thống định mức dự toán xây dựng công trình",
  "b. Công bố giá vật liệu xây dựng, đơn giá nhân công xây dựng, giáca máy và thiết bị thi công, chỉ số giá xây dựng và đơn giá xây dựngcông trình.",
  "c. Công bố suất vốn đầu tư xây dựng công trình",
  "d. Cả a và c",
  "b",
  " Thẩm quyền điều chỉnh cơ cấu các khoản mục chi phí trongtổng mức đầu tư xây dựng của dự án đầu tư xây dựng do cơquan nào sau đây?",
  "a. Người quyết định đầu tư quyết định.",
  "b. Chủ đầu tư tổ chức điều chỉnh, báo cáo người quyết định đầu tưvà chịu trách nhiệm về việc điều chỉnh của mình.",
  "c. Chủ đầu tư tổ chức điều chỉnh theo ủy quyền của Người quyếtđịnh đầu tư.",
  "d. Các đáp án trên đều sai.",
  "b",
  " Việc thẩm định tổng mức đầu tư xây dựng của dự án đầu tư xâydựng theo hình thức PPP, do cơ quan nào dưới đây thẩm định?",
  "a. Cơ quan chuyên môn về xây dựng thuộc Bộ Xây dựng, Bộ quản lýcông trình xây dựng chuyên ngành.",
  "b. Sở Xây dựng, Sở quản lý công trình xây dựng chuyên ngành.",
  "c. Đơn vị đầu mối quản lý về hoạt động PPP thuộc cơ quan nhànước có thẩm quyền ký kết hợp đồng dự án chủ trì.",
  "d. Nhà đầu tư.",
  "c",
  " Dự án xây dựng Trụ sở văn phòng Tổng cục Thuế có tổng mứcđầu tư 180 tỷ đồng. Theo quy định của Luật Xây dựng 2014 vàcác văn bản quy phạm pháp luật hướng dẫn Luật, tổng mức đầutư xây dựng của dự án này do cơ quan nào dưới đây thẩmđịnh?",
  "a. Cơ quan chuyên môn về xây dựng thuộc Bộ Xây dựng thẩm định",
  "b. Sở Xây dựng thẩm định",
  "c. Cơ quan chuyên môn trực thuộc người quyết định đầu tư chủ trì tổchức thẩm định.",
  "d. Các đáp án trên đều sai.",
  "a",
  " Dự toán xây dựng công trình sử dụng vốn ngân sách (giai đoạnthiết kế bản vẽ thi công - trường hợp thiết kế ba bước), do cơquan nào dưới đây phê duyệt?",
  "a. Người quyết định đầu tư phê duyệt.",
  "b. Chủ đầu tư phê duyệt.",
  "c. Người quyết định đầu tư ủy quyền cho Chủ đầu tư phê duyệt.",
  "d. Các đáp án trên đều sai.",
  "b",
  " Đáp án nào dưới đây liệt kê đúng và đủ các khoản mục chi phíthuộc chi phí xây dựng trong dự toán xây dựng công trình?",
  "a. Chi phí vật liệu, nhân công, máy và thiết bị thi công, chi phí chung,lợi nhuận của doanh nghiệp xây dựng.",
  "b. Chi phí trực tiếp, chi phí quản lý của doanh nghiệp, chi phí điềuhành sản xuất tại công trường, chi phí phục vụ công nhân, chi phíphục vụ thi công tại công trường và một số chi phí phục vụ cho quảnlý khác của doanh nghiệp và lợi nhuận của doanh nghiệp xây dựng.",
  "c. Tất cả các chi phí trực tiếp tạo nên sản phẩm xây dựng, lợi nhuậncủa doanh nghiệp xây dựng và thuế giá trị gia tăng.",
  "d. Chi phí trực tiếp, chi phí chung, thu nhập chịu thuế tính trước,thuếgiá trị gia tăng.",
  "d",
  " Kể từ ngày nhận đủ hồ sơ đề nghị thanh toán vốn đầu tư hợplệ, cơ quan cấp phát, cho vay có trách nhiệm thanh toán vốnđầu tư trong thời hạn bao nhiêu ngày?",
  "a. 6 ngày làm việc;",
  "b. 7 ngày làm việc;",
  "c. 8 ngày làm việc;",
  "d. 14 ngày làm việc.",
  "b",
  " Hợp đồng thi công xây dựng gói thầu A được ký kết giữa bêngiao thầu và bên nhận thầu có giá trị hợp đồng là 40 tỷ, trongtrường hợp này, giá trị tạm ứng tối thiểu cho hợp đồng xâydựng này là bao nhiêu?",
  "a. 20% giá hợp đồng;",
  "b. 15% giá hợp đồng;",
  "c. 10% giá hợp đồng;",
  "d. 25% giá hợp đồng.",
  "b",
  " Hợp đồng tư vấn xây dựng được áp dụng các loại giá hợp đồngnào sau đây?",
  "a. Hợp đồng trọn gói;",
  "b. Hợp đồng theo đơn giá (cố định và điều chỉnh);",
  "c. Hợp đồng theo thời gian;",
  "d. Tất cả các loại giá hợp đồng nêu trên.",
  "d",
  " Hợp đồng tư vấn xây dựng gói thầu B được ký kết giữa bêngiao thầu và bên nhận thầu có giá trị hợp đồng là 25 tỷ. Vậy, giátrị tạm ứng tối thiểu cho hợp đồng xây dựng này là bao nhiêu?",
  "a. 10% giá hợp đồng;",
  "b. 15% giá hợp đồng;",
  "c. 20% giá hợp đồng;",
  "d. 25% giá hợp đồng.",
  "b",
  " Hợp đồng thi công xây dựng gói thầu C được ký kết giữa bêngiao thầu và bên nhận thầu có giá hợp đồng là 100 tỷ. Theo thỏathuận hợp đồng, bên giao thầu sẽ tạm ứng hợp đồng cho bênnhận thầu 30 là tỷ (30% giá hợp đồng). Theo quy định của Nghịđịnh số 37/2015/NĐ-CP, thì phần giá trị hợp đồng tối thiểukhông được điều chỉnh giá đối với hợp đồng xây dựng này làbao nhiêu % kể từ thời điểm tạm ứng?",
  "a. 10% giá hợp đồng;",
  "b. 15% giá hợp đồng;",
  "c. 20% giá hợp đồng;",
  "d. 25% giá hợp đồng.",
  "b",
  " Mức tạm ứng hợp đồng xây dựng tối đa được là bao nhiêu %giá hợp đồng?",
  "a. 40% giá hợp đồng;",
  "b. 50% giá hợp đồng;",
  "c. 60% giá hợp đồng:",
  "d. 80% giá hợp đồng.",
  "b",
  " Hợp đồng xây dựng nào sau đây thuộc phạm vi điều chỉnh củaNghị định số 37/2015/NĐ-CP?",
  "a. Hợp đồng xây dựng được ký kết giữa nhà đầu tư thực hiện dự ánPPP và nhà thầu thực hiện các gói thầu;",
  "b. Hợp đồng xây dựng thuộc các dự án đầu tư xây dựng có sử dụngvốn nhà nước, vốn của doanh nghiệp nhà nước từ 30% trở lên trongtổng mức đầu tư của dự án;",
  "c. Hợp đồng xây dựng thuộc các dự án đầu tư xây dựng có sử dụngvốn nhà nước, vốn của doanh nghiệp nhà nước dưới 30% nhữngtrên 500 tỷ đồng trong tổng mức đầu tư của dự án;",
  "d. Cả a, b, c.",
  "d",
  " Thời điểm có hiệu lực của hợp đồng xây dựng là thời điểm nàotrong các trường hợp sau đây?",
  "a. Thời điểm ký kết hợp đồng (đóng dấu nếu có)",
  "b. Thời điểm cụ thể do các bên thỏa thuận trong hợp đồng xây dựngvà bên giao thầu đã nhận được bảo đảm thực hiện hợp đồng củabên nhận thầu (đối với hợp đồng có quy định về bảo đảm thực hiệnhợp đồng);",
  "c. Thời điểm ký kết hợp đồng (đóng dấu nếu có) và bên giao thầu đãnhận được bảo đảm thực hiện hợp đồng của bên nhận thầu (đối vớihợp đồng có quy định về bảo đảm thực hiện hợp đồng);",
  "d. Thời điểm ký kết hợp đồng (đóng dấu nếu có) hoặc thời điểm cụthể do các bên thỏa thuận trong hợp đồng xây dựng và bên giaothầu đã nhận được bảo đảm thực hiện hợp đồng của bên nhận thầu(đối với hợp đồng có quy định về bảo đảm thực hiện hợp đồng).",
  "d",
  " Hợp đồng thi công xây dựng công trình được thanh lý khi nào?",
  "a. Khi nghiệm thu, hoàn thành hạng mục công trình, công trình đưavào sử dụng;",
  "b. Khi hết thời hạn bảo hành;",
  "c. Khi bên nhận thầu đã hoàn thành nghĩa vụ bảo hành hạng mụccông trình,công trình;",
  "d. Khi bên giao thầu và bên nhận thầu đã hoàn thành tất cả cácnghĩa vụ theo hợp đồng xây dựng đã ký.",
  "d",
  " Hợp đồng thi công xây dựng công trình có giá trọn gói, đượcđiều chỉnh theo những trường hợp nào dưới đây?",
  "a. Khi khối lượng công việc nằm ngoài phạm vi công việc phải thựchiện của thiết kế theo hợp đồng.",
  "b. Khi xảy ra bất khả kháng được Chủ đầu tư chấp thuận",
  "c. Khi điều chỉnh biện pháp thi công",
  "d. Khi khối lượng công việc thực tế hoàn thành được nghiệm thutăng hoặc giảm so với khối lượng công việc tương ứng ghi trong hợpđồng.",
  "a",
  " Đối với hợp đồng theo đơn giá điều chỉnh, trường hợp nàodưới đây không phải thực hiện ký kết phụ lục bổ sung hợpđồng?",
  "a. Khối lượng thực tế hoàn thành được nghiệm thu tăng hoặc giảmlớn hơn 20% khối lượng công việc tương ứng ghi trong hợp đồng.",
  "b. Bổ sung khối lượng công việc hợp lý chưa có đơn giá trong hợpđồng.",
  "c. Điều chỉnh đơn giá toàn bộ hoặc một số đơn giá cho những côngviệc mà tại thời điểm ký hợp đồng bên giao thầu và bên nhận thầuđã thỏa thuận điều chỉnh sau một khoảng thời gian nhất định kể từngày hợp đồng có hiệu lực.",
  "d. Các trường hợp bất khả kháng và bất khả kháng khác theo quyđịnh.",
  "c",
  " Chi phí nào dưới đây không được coi là chi phí tư vấn đầu tưxây dựng?",
  "a. Chi phí lập báo cáo đánh giá tác động môi trường.",
  "b. Chi phí quan trắc biến dạng công trình.",
  "c. Chi phí kiểm định chất lượng công trình.",
  "d. Chi phí quy đổi vốn đầu tư xây dựng công trình.",
  "b",
  " Chi phí thuê tư vấn nước ngoài thực hiện công việc lập nhiệmvụ, lập đồ án quy hoạch được giới hạn trong khoảng nào sauđây:",
  "a. Không vượt quá 2 lần mức chi phí do tư vấn trong nước thực hiệnxác định theo quy định của pháp luật.",
  "b. Không vượt quá 3 lần mức chi phí do tư vấn trong nước thực hiệnxác định theo quy định của pháp luật.",
  "c. Không vượt quá 3,5 lần mức chi phí do tư vấn trong nước thựchiện xác định theo quy định của pháp luật.",
  "d. Không phương án nào đúng.",
  "c",
  " Dự toán gói thầu tư vấn nước ngoài được xác định trên cơ sởnào dưới đây?",
  "a. Chi phí tư vấn nước ngoài dự tính trong tổng mức đầu tư",
  "b. Lập dự toán tháng - người (hoặc ngày - người)",
  "c. Định mức chi phí thuê tư vấn nước ngoài",
  "d. Dự toán chi phí tư vấn nước ngoài",
  "d",
  " Dự toán gói thầu tư vấn đầu tư xây dựng bao gồm các chi phínào sau đây?",
  "a. Chi phí chuyên gia, chi phí quản lý, chi phí khác, thu nhập chịu thuế tính trước",
  "b. Chi phí chuyên gia, chi phí khác, thu nhập chịu thuế tính trước, chiphí dự phòng",
  "c. Chi phí chuyên gia, chi phí quản lý, chi phí khác, thu nhập chịuthuế tính trước, thuế và chi phí dự phòng.",
  "d. Chi phí chuyên gia, chi phí quản lý, chi phí khác, thu nhập chịuthuế tính trước và thuế.",
  "c",
  " Nhà thầu tư vấn quản lý chi phí đầu tư xây dựng có quyền nàosau đây?",
  "a. Quyết định định mức xây dựng, giá xây dựng và các chi phí kháccó liên quan khi xác định giá dự thầu để tham gia đấu thầu",
  "b. Kiểm soát các thay đổi trong quá trình thi công xây dựng côngtrình có liên quan đến thay đổi chi phí đầu tư xây dựng công trìnhhoặc đẩy nhanh tiến độ xây dựng công trình",
  "c. Xem xét, chấp thuận các đề xuất thay đổi về giá vật tư, vật liệuxây dựng theo đề xuất của tư vấn thiết kế hoặc nhà thầu thi côngxây dựng",
  "d. Yêu cầu chủ đầu tư thanh toán các khoản chi phí theo hợp đồngđã ký kết; được thanh toán các khoản vay do chậm thanh toán.",
  "d",
  " Nghĩa vụ nào sau đây là của nhà thầu tư vấn quản lý chi phí đầutư xây dựng?",
  "a. Chịu trách nhiệm trước pháp luật và chủ đầu tư về kết quả thựchiện công việc tư vấn của mình và bồi thường thiệt hại gây ra chochủ đầu tư (nếu có) theo hợp đồng đã ký kết và pháp luật có liênquan",
  "b. Tổ chức xác định các định mức dự toán xây dựng mới hoặc điềuchỉnh của công trình làm cơ sở quản lý chi phí đầu tư xây dựng",
  "c. Tổ chức kiểm soát chi phí đầu tư xây dựng công trình theo quyđịnh",
  "d. Cả 3 phương án trên",
  "a",
  " Quyền nào sau đây là quyền của chủ đầu tư trong quản lý chiphí đầu tư xây dựng?",
  "a. Chấp thuận thực hiện lựa chọn tổ chức tư vấn quản lý chi phí đầutư xây dựng đủ điều kiện năng lực theo quy định tại Nghị định vềquản lý dự án đầu tư xây dựng để thực hiện thẩm tra tổng mức đầutư, dự toán xây dựng công trình làm cơ sở cho việc thẩm định, phêduyệt.",
  "b. Quyết định phương pháp xác định tổng mức đầu tư.",
  "c. Điều chỉnh cơ cấu các khoản mục chi phí trong tổng mức đầu tưnhưng không làm vượt tổng mức đầu tư đã được phê duyệt.",
  "d. Phương án b, c",
  "d",
  " Chi phí nào dưới đây không thuộc thành phần chi phí hạng mụcchung?",
  "a. Chi phí nhà tạm tại hiện trường để ở và điều hành thi công.",
  "b. Chi phí thí nghiệm vật liệu của nhà thầu.",
  "c. Chi phí quan trắc biến dạng công trình.",
  "d. Chi phí đảm bảo an toàn giao thông phục vụ thi công (nếu có).",
  "c"];